### ISSUE TITLE
Failed to convert from type java.lang.String to type java.math.BigInteger [DATAMONGO-342]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-mongodb#1275]
**[drypot](https://jira.spring.io/secure/ViewProfile.jspa?name=drypot)** opened **[DATAMONGO-342](https://jira.spring.io/browse/DATAMONGO-342?redirect=false)** and commented

Normal `String` field tried to be converted to `BigInteger`.

```
org.springframework.core.convert.ConversionFailedException: Failed to convert from type java.lang.String to type java.math.BigInteger for value 'KKaK'; nested exception is java.lang.NumberFormatException: For input string: "KKaK"
	at org.springframework.core.convert.support.ConversionUtils.invokeConverter(ConversionUtils.java:41)
	at org.springframework.core.convert.support.GenericConversionService.convert(GenericConversionService.java:170)
	at org.springframework.core.convert.support.GenericConversionService.convert(GenericConversionService.java:154)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.getPotentiallyConvertedSimpleWrite(MappingMongoConverter.java:604)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.writeSimpleInternal(MappingMongoConverter.java:585)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.access$100(MappingMongoConverter.java:73)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter$4.doWithPersistentProperty(MappingMongoConverter.java:370)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter$4.doWithPersistentProperty(MappingMongoConverter.java:357)
	at org.springframework.data.mapping.model.BasicPersistentEntity.doWithProperties(BasicPersistentEntity.java:173)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.writeInternal(MappingMongoConverter.java:357)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.writeInternal(MappingMongoConverter.java:329)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.write(MappingMongoConverter.java:294)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.write(MappingMongoConverter.java:73)
	at org.springframework.data.mongodb.core.MongoTemplate.doInsert(MongoTemplate.java:615)
	at org.springframework.data.mongodb.core.MongoTemplate.insert(MongoTemplate.java:577)
	at org.springframework.data.mongodb.core.MongoTemplate.insert(MongoTemplate.java:568)
```

---

**Affects:** 1.0 RC1

**Reference URL:** http://forum.springsource.org/showthread.php?119805-spring-mongodb-rc1-bug

**Attachments:**
- [mylyn-context.zip](https://jira.spring.io/secure/attachment/19226/mylyn-context.zip) (_3.60 kB_)

**Referenced from:** commits https://github.com/spring-projects/spring-data-mongodb/commit/0ad0dad124df401729d7072487b8712ae3329b5b, https://github.com/spring-projects/spring-data-mongodb/commit/8206b5f950c0ade1517a5b074c9faf33a07c0381

1 votes, 1 watchers

**Comment by lukas0krupa** [comment]
Apologies for bothering, but are you sure it is still working?

Unfortunately, I can't work with SNAPSHOTs and at the moment `spring-data-mongodb@5.1.1` (got through `spring-boot-starter-mongodb@4.1.1`) does same behaviour as explained in comment below. Any chance you can point me to right direction?

After upgrade, I removed all custom converters (sort out my problem), however, got some old tests which are using older DB dumps where BIgInteger is stored with radix 16, rather than default radix 10. Recreating those dumps (in order to get tests working) would be painfull.

Although I will survive, I though I will point this up just in case this behaviour is not intended.

> **[drypot](https://jira.spring.io/secure/ViewProfile.jspa?name=drypot)** commented
> 
> In my case, there is no `StringConverter`. It's just simple `String` field, but Spring Mongo tries save it as `BigInteger`.
> 
> @Document
> @CompoundIndexes({
> 	@CompoundIndex(name="categoryIdx", def = "{'categoryId' : 1, 'udate' : -1}")
> })
> public class PostThread {
> 
> 	@Id
> 	private int id;
> 
> 	private int categoryId;
> 
> 	private int hit;
> 
> 	private int length;
> 
> 	private DateTime cdate;
> 
> 	private DateTime udate;
> 
> 	private String userName;
> 
> 	private String title;
> …
> }
> Problem occurs at storing `String userName` field.
> 
> Additional comment, I use JodaTime `DateToDateTimeConverter`.
> 
> @Override
> protected void afterMappingMongoConverterCreation(MappingMongoConverter converter) {
> 	super.afterMappingMongoConverterCreation(converter);
> 	converter.setTypeMapper(new DefaultMongoTypeMapper(null));
> 
> 	CustomConversions conversions = new CustomConversions(Arrays.asList(
> 			DateToDateTimeConverter.INSTANCE,
> 			DateTimeToDateConverter.INSTANCE
> 	));
> 	converter.setCustomConversions(conversions);
> }
> 
> …
> 
> public enum DateTimeToDateConverter implements Converter<DateTime, Date> {
> 	INSTANCE;
> 
> 	public Date convert(DateTime source) {
> 		return source == null ? null : source.toDate();
> 	}
> }
