### ISSUE TITLE
Stackoverflow when querying document with cycle reference using @DBRef [DATAMONGO-488]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-mongodb#1368]
**[Ludovic Praud](https://jira.spring.io/secure/ViewProfile.jspa?name=ludovic.praud)** opened **[DATAMONGO-488](https://jira.spring.io/browse/DATAMONGO-488?redirect=false)** and commented

Given two documents which reference each other with a DBRef

```
@Document
class Site {
    @DBRef User admin;
}

@Document
class User {
    @DBRef Site site;
}

Site siteSaved = siteRepository.save(new Site());
User userSaved = userRepository.save(new User(siteSaved));
siteSaved.setAdmin(userSaved);
siteRepository.save(siteSaved);

siteRepository.findOne(siteSaved.id); // stackoverflow here
```

```
java.lang.StackOverflowError
	at org.bson.BasicBSONEncoder._put(BasicBSONEncoder.java:417)
	at org.bson.BasicBSONEncoder.putObjectId(BasicBSONEncoder.java:388)
	at org.bson.BasicBSONEncoder._putObjectField(BasicBSONEncoder.java:188)
	at org.bson.BasicBSONEncoder.putObject(BasicBSONEncoder.java:121)
	at org.bson.BasicBSONEncoder.putObject(BasicBSONEncoder.java:86)
	at com.mongodb.DefaultDBEncoder.writeObject(DefaultDBEncoder.java:27)
	at com.mongodb.OutMessage.putObject(OutMessage.java:142)
	at com.mongodb.OutMessage._appendQuery(OutMessage.java:85)
	at com.mongodb.OutMessage.query(OutMessage.java:44)
	at com.mongodb.OutMessage.query(OutMessage.java:38)
	at com.mongodb.DBApiLayer$MyCollection.__find(DBApiLayer.java:303)
	at com.mongodb.DBCollection.findOne(DBCollection.java:332)
	at com.mongodb.DBCollection.findOne(DBCollection.java:318)
	at com.mongodb.DBRefBase.fetch(DBRefBase.java:52)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter$DelegatingParameterValueProvider.getParameterValue(MappingMongoConverter.java:950)
	at org.springframework.data.mapping.model.BeanWrapper.<init>(BeanWrapper.java:115)
	at org.springframework.data.mapping.model.BeanWrapper.create(BeanWrapper.java:73)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.read(MappingMongoConverter.java:217)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.read(MappingMongoConverter.java:200)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.getValueInternal(MappingMongoConverter.java:712)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter$2.doWithAssociation(MappingMongoConverter.java:239)
	at org.springframework.data.mapping.model.BasicPersistentEntity.doWithAssociations(BasicPersistentEntity.java:185)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.read(MappingMongoConverter.java:236)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.read(MappingMongoConverter.java:200)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter$DelegatingParameterValueProvider.getParameterValue(MappingMongoConverter.java:950)
	at org.springframework.data.mapping.model.BeanWrapper.<init>(BeanWrapper.java:115)
	at org.springframework.data.mapping.model.BeanWrapper.create(BeanWrapper.java:73)
```

As a workaround I can break this cycle and only reference Site from User and add an isAdmin property to User class but I think it is less direct and clear this way. It requires one more query to retrieve the admin of a Site.

I fell that it is because retrieving a document from DBRef is not lazy as asked in [DATAMONGO-348](https://jira.spring.io/browse/DATAMONGO-348), but I thought it was eager only for one level depth

---

**Affects:** 1.0.2

**Issue Links:**
- [DATAMONGO-348](https://jira.spring.io/browse/DATAMONGO-348) Lazy Load for DbRef

**Referenced from:** pull request https://github.com/spring-projects/spring-data-mongodb/pull/12

8 votes, 9 watchers

**Comment by MLyousfi** [comment]
> **[Oliver Drotbohm](https://jira.spring.io/secure/ViewProfile.jspa?name=olivergierke)** commented
> 
> Looking at both of the samples given the reason for the exception is quite obvious. You have a bi-directional relationship implemented with `DBRef`. As we're eagerly resolving the `DBRef` instances we get into a ping pong situation here. While we of course wil generally think about a solution to this, I think it's advisable to avoid circular dependencies between domain objects and essentially break them up by replacing one relationship with a repository (i.e. query) call. So for the `Account` / `Person` scenario I think a reasonable workaround is removing the `Account` property from the `Person` class and rather introduce a `List<Account> findByPerson(Person person);` on an `AccountRepository` to break the cyclic dependency
> 

so how can we implement a many to many relationship ?
