### ISSUE TITLE
Combining BeanPostProcessor with mongodb repository raises java.lang.IllegalStateException [DATAMONGO-817]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-data-mongodb#1742]
**[Thibault Kruse](https://jira.spring.io/secure/ViewProfile.jspa?name=tkruse)** opened **[DATAMONGO-817](https://jira.spring.io/browse/DATAMONGO-817?redirect=false)** and commented

When Defining a BeanPostProcessor Bean that depends on a Mongo Repository, startup fails with complicated looking exception:

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.379 sec <<< FAILURE! - in org.springframework.boot.sample.data.mongo.SampleMongoApplicationTests
testDefaultSettings(org.springframework.boot.sample.data.mongo.SampleMongoApplicationTests)  Time elapsed: 1.352 sec  <<< ERROR!
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sampleMongoApplication': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.springframework.boot.sample.data.mongo.CustomerRepository org.springframework.boot.sample.data.mongo.SampleMongoApplication.repository; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'customerRepository': FactoryBean threw exception on object creation; nested exception is java.lang.IllegalStateException: ApplicationEventMulticaster not initialized - call 'refresh' before multicasting events via the context: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@540984b: startup date [Sat Dec 21 19:07:22 CET 2013]; root of context hierarchy
at org.springframework.context.support.AbstractApplicationContext.getApplicationEventMulticaster(AbstractApplicationContext.java:346)
at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:333)
at org.springframework.data.mapping.context.AbstractMappingContext.addPersistentEntity(AbstractMappingContext.java:268)
at org.springframework.data.mapping.context.AbstractMappingContext.getPersistentEntity(AbstractMappingContext.java:168)
at org.springframework.data.mapping.context.AbstractMappingContext.getPersistentEntity(AbstractMappingContext.java:137)
at org.springframework.data.mapping.context.AbstractMappingContext.getPersistentEntity(AbstractMappingContext.java:63)
at org.springframework.data.mongodb.repository.support.MongoRepositoryFactory.getEntityInformation(MongoRepositoryFactory.java:141)
at org.springframework.data.mongodb.repository.support.MongoRepositoryFactory.getTargetRepository(MongoRepositoryFactory.java:83)
at org.springframework.data.repository.core.support.RepositoryFactorySupport.getRepository(RepositoryFactorySupport.java:150)
at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.getObject(RepositoryFactoryBeanSupport.java:162)
at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.getObject(RepositoryFactoryBeanSupport.java:44)
at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:144)
at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.getObjectFromFactoryBean(FactoryBeanRegistrySupport.java:103)
at org.springframework.beans.factory.support.AbstractBeanFactory.getObjectForBeanInstance(AbstractBeanFactory.java:1514)
at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315)
at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:195)

Example will be provided as pull request on spring-issues...

---

1 votes, 3 watchers

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
