### ISSUE TITLE
Serialization exception in Query class with enumerations [DATAMONGO-1037]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-data-mongodb#1960]
**[Poorna Subhash](https://jira.spring.io/secure/ViewProfile.jspa?name=poornasubhash)** opened **[DATAMONGO-1037](https://jira.spring.io/browse/DATAMONGO-1037?redirect=false)** and commented

When enum value is used as part of `Criteria` object, when `Query` is throwing exception, serialization is failing.
Following is stacktrace:

```
java.lang.RuntimeException: json can't serialize type : class mypackage.MyClass$UserStatus
	at com.mongodb.util.ClassMapBasedObjectSerializer.serialize(ClassMapBasedObjectSerializer.java:77)
	at com.mongodb.util.JSONSerializers$MapSerializer.serialize(JSONSerializers.java:317)
	at com.mongodb.util.ClassMapBasedObjectSerializer.serialize(ClassMapBasedObjectSerializer.java:79)
	at com.mongodb.util.JSONSerializers$MapSerializer.serialize(JSONSerializers.java:317)
	at com.mongodb.util.ClassMapBasedObjectSerializer.serialize(ClassMapBasedObjectSerializer.java:79)
	at com.mongodb.util.JSON.serialize(JSON.java:55)
	at com.mongodb.util.JSON.serialize(JSON.java:40)
	at com.mongodb.BasicDBObject.toString(BasicDBObject.java:83)
	at java.lang.String.valueOf(String.java:2854)
	at java.lang.StringBuilder.append(StringBuilder.java:128)
	at org.springframework.data.mongodb.core.query.Query.addCriteria(Query.java:88)
```

Also on side note (may qualify for another bug which caused above exception to appear) : MongoDB allows same multiple criteria on same key, For e.g., db.business.find({status:'Active', status:{$ne:'InActive'}},{status:1}) is working fine from mongodb console. If I try same thing using Criteria it causes exception. I can work around the problem, but in certain cases I would like to allow this where criteria is prepared dynamically.

---

**Affects:** 1.5.2 (Dijkstra SR2)

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
