### ISSUE TITLE
"Owning type must not be null!" sounds a bit unclear to me [DATAMONGO-1435]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-data-mongodb#2346]
**[Julien Graglia](https://jira.spring.io/secure/ViewProfile.jspa?name=jgraglia)** opened **[DATAMONGO-1435](https://jira.spring.io/browse/DATAMONGO-1435?redirect=false)** and commented

Hi,

I was facing a "pb" with the query of dynamic properties of a bean : I ran into the following exception :

```

java.lang.IllegalArgumentException: Owning type must not be null!

	at org.springframework.util.Assert.notNull(Assert.java:115)
	at org.springframework.data.mapping.PropertyPath.<init>(PropertyPath.java:70)
	at org.springframework.data.mapping.PropertyPath.create(PropertyPath.java:329)
```

I finally found a way to workaround my pb. ie
use

```java
private final Map<String, Object> details;
```

and not

```java
private final Map details;
```

Now it sound "obvious"  but I have suspected a lombok pb, or the fact that I don't want to use `@Document` annotations and so.

Not sure what should be great/better/helpfull for others but may be a way to detect a non generic Map? or fail fast? or handle as Object when not declared?

See
https://github.com/jgraglia/springmongobug for a simple maven project demonstrating my pb, and the fix.

Thx !

---
No further details from [DATAMONGO-1435](https://jira.spring.io/browse/DATAMONGO-1435?redirect=false)

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
