### ISSUE TITLE
DEBUG message java.lang.ClassNotFoundException: javax.annotation.Nullable when starting with Querydsl [DATAMONGO-1512]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-data-mongodb#2423]
**[prasanna ganesh](https://jira.spring.io/secure/ViewProfile.jspa?name=nprasannaganesh)** opened **[DATAMONGO-1512](https://jira.spring.io/browse/DATAMONGO-1512?redirect=false)** and commented

Hello Team,
I'm not sure this is the right forum for mentioning the issue i'm facing after upgrading to latest mongo java driver version to 3.2.2, spring-data-mongodb to 1.9.4.RELEASE, spring-data-commons to 1.12.1 and Spring framework version to 4.2.8.RELEASE.

As part of server startup logs i'm keep getting below error which i'm unable to resolve. As per my understanding all required dependencies are available in my pom.xml file, but still i'm facing the issue. Any suggestion will be helpful. Excuse me if its not right place.

Tried adding dependency jsr305 from com.google.code.findbugs but still seeing same exceptions

Exception details:

_

```java
1.9.4.RELEASE.jar!/org/springframework/data/mongodb/repository/support/SpringDataMongodbQuery.class], URL [jar:file:/C:/Dev/spring-tool-suite-3.8.0.RELEASE-e4.6-win32-x86_64/sts-bundle/pivotal-tc-server-developer-3.1.4.RELEASE/base-instance/wtpwebapps/ip_vctc_svcs_customerrules/WEB-INF/lib/spring-data-mongodb-1.9.4.RELEASE.jar!/org/springframework/data/mongodb/repository/support/SpringDataMongodbSerializer.class]]
08:13:18.046 [localhost-startStop-1] DEBUG o.s.d.r.c.RepositoryConfigurationDelegate$LenientAssignableTypeFilter - Could not read super class [com.querydsl.apt.AbstractQuerydslProcessor] of type-filtered class [org.springframework.data.mongodb.repository.support.MongoAnnotationProcessor]
08:13:18.048 [localhost-startStop-1] DEBUG o.s.c.a.ClassPathScanningCandidateComponentProvider - Identified candidate component class: URL [jar:file:/C:/Dev/spring-tool-suite-3.8.0.RELEASE-e4.6-win32-x86_64/sts-bundle/pivotal-tc-server-developer-3.1.4.RELEASE/base-instance/wtpwebapps/ip_vctc_svcs_customerrules/WEB-INF/lib/spring-data-mongodb-1.9.4.RELEASE.jar!/org/springframework/data/mongodb/repository/support/MongoRepositoryFactory.class]
08:13:18.062 [localhost-startStop-1] DEBUG o.s.c.t.c.AnnotationAttributesReadingVisitor - Failed to class-load type while reading annotation metadata. This is a non-fatal error, but certain annotation metadata may be unavailable.
java.lang.ClassNotFoundException: javax.annotation.Nullable
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1305) ~[catalina.jar:na]
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1139) ~[catalina.jar:na]
	at org.springframework.core.type.classreading.RecursiveAnnotationAttributesVisitor.visitEnd(RecursiveAnnotationAttributesVisitor.java:47) ~[spring-core-4.2.8.RELEASE.jar:4.2.8.RELEASE]
	at org.springframework.asm.ClassReader.readAnnotationValues(ClassReader.java:1802) [spring-core-4.2.8.RELEASE.jar:4.2.8.RELEASE]
	at org.springframework.asm.ClassReader.readMethod(ClassReader.java:976) [spring-core-4.2.8.RELEASE.jar:4.2.8.RELEASE]
	at org.springframework.asm.ClassReader.accept(ClassReader.java:695) [spring-core-4.2.8.RELEASE.jar:4.2.8.RELEASE]
	at org.springframework.asm.ClassReader.accept(ClassReader.java:508) [spring-core-4.2.8.RELEASE.jar:4.2.8.RELEASE]
	at org.springframework.core.type.classreading.SimpleMetadataReader.<init>(SimpleMetadataReader.java:64) [spring-core-4.2.8.RELEASE.jar:4.2.8.RELEASE]
	at org.springframework.core.type.classreading.SimpleMetadataReaderFactory.getMetadataReader(SimpleMetadataReaderFactory.java:98) [spring-core-4.2.8.RELEASE.jar:4.2.8.RELEASE]
	at org.springframework.core.type.classreading.CachingMetadataReaderFactory.getMetadataReader(CachingMetadataReaderFactory.java:102) [spring-core-4.2.8.RELEASE.jar:4.2.8.RELEASE]
	at org.springframework.core.type.classreading.SimpleMetadataReaderFactory.getMetadataReader(SimpleMetadataReaderFactory.java:93) [spring-core-4.2.8.RELEASE.jar:4.2.8.RELEASE]
	at org.springframework.core.type.filter.AbstractTypeHierarchyTraversingFilter.match(AbstractTypeHierarchyTraversingFilter.java:121) [spring-core-4.2.8.RELEASE.jar:4.2.8.RELEASE]
	at org.springframework.core.type.filter.AbstractTypeHierarchyTraversingFilter.match(AbstractTypeHierarchyTraversingFilter.java:105) [spring-core-4.2.8.RELEASE.jar:4.2.8.RELEASE]
	at org.springframework.data.repository.config.RepositoryConfigurationDelegate$LenientAssignableTypeFilter.match(RepositoryConfigurationDelegate.java:202) [spring-data-commons-1.12.1.RELEASE.jar:na]
	at org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider.isCandidateComponent(ClassPathScanningCandidateComponentProvider.java:346) [spring-context-4.2.8.RELEASE.jar:4.2.8.RELEASE]
	at org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider.findCandidateComponents(ClassPathScanningCandidateComponentProvider.java:280) [spring-context-4.2.8.RELEASE.jar:4.2.8.RELEASE]
	at org.springframework.data.repository.config.RepositoryConfigurationDelegate.multipleStoresDetected(RepositoryConfigurationDelegate.java:167) [spring-data-commons-1.12.1.RELEASE.jar:na]
	at org.springframework.data.repository.config.RepositoryConfigurationDelegate.<init>(RepositoryConfigurationDelegate.java:88) [spring-data-commons-1.12.1.RELEASE.jar:na]
	at org.springframework.data.repository.config.RepositoryBeanDefinitionRegistrarSupport.registerBeanDefinitions(RepositoryBeanDefinitionRegistrarSupport.java:80) [spring-data-commons-1.12.1.RELEASE.jar:na]
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsFromRegistrars(ConfigurationClassBeanDefinitionReader.java:352) [spring-context-4.2.8.RELEASE.jar:4.2.8.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForConfigurationClass(ConfigurationClassBeanDefinitionReader.java:143) [spring-context-4.2.8.RELEASE.jar:4.2.8.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitions(ConfigurationClassBeanDefinitionReader.java:116) [spring-context-4.2.8.RELEASE.jar:4.2.8.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:333) [spring-context-4.2.8.RELEASE.jar:4.2.8.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:243) [spring-context-4.2.8.RELEASE.jar:4.2.8.RELEASE]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:273) [spring-context-4.2.8.RELEASE.jar:4.2.8.RELEASE]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:98) [spring-context-4.2.8.RELEASE.jar:4.2.8.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:678) [spring-context-4.2.8.RELEASE.jar:4.2.8.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:520) [spring-context-4.2.8.RELEASE.jar:4.2.8.RELEASE]
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:444) [spring-web-4.2.8.RELEASE.jar:4.2.8.RELEASE]
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:326) [spring-web-4.2.8.RELEASE.jar:4.2.8.RELEASE]
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:107) [spring-web-4.2.8.RELEASE.jar:4.2.8.RELEASE]
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4811) [catalina.jar:na]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5251) [catalina.jar:na]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147) [catalina.jar:na]
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725) [catalina.jar:na]
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701) [catalina.jar:na]
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717) [catalina.jar:na]
	at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:587) [catalina.jar:8.0.33.A]
	at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1798) [catalina.jar:8.0.33.A]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [na:1.8.0_101]
	at java.util.concurrent.FutureTask.run(Unknown Source) [na:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_101]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_101]
08:13:18.065 [localhost-startStop-1] DEBUG o.s.d.r.c.RepositoryConfigurationDelegate$LenientAssignableTypeFilter - Could not read super class [com.querydsl.mongodb.AbstractMongodbQuery] of type-filtered class [org.springframework.data.mongodb.repository.support.SpringDataMongodbQuery]
08:13:18.067 [localhost-startStop-1] DEBUG o.s.d.r.c.RepositoryConfigurationDelegate$LenientAssignableTypeFilter - Could not read super class [com.querydsl.mongodb.MongodbSerializer] of type-filtered class [org.springframework.data.mongodb.repository.support.SpringDataMongodbSerializer]
08:13:18.068 [localhost-startStop-1] DEBUG o.s.c.e.StandardEnvironment - Adding [systemProperties] PropertySource with lowest search precedence
08:13:18.068 [localhost-startStop-1] DEBUG o.s.c.e.StandardEnvironment - Adding [systemEnvironment] PropertySource with lowest search precedence
08:13:18.068 [localhost-startStop-1] DEBUG o.s.c.e.StandardEnvironment - Initialized StandardEnvironment with PropertySources [systemProperties,systemEnvironment]
```

_

```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	
	<version>0.0.1-SNAPSHOT</version>
	<packaging>pom</packaging>
	<name>ip_vctc_svcs</name>
	<description>parent module</description>

	<properties>
		<junit.version>4.11</junit.version>
		<qa.version>2.4.0-SNAPSHOT</qa.version>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<org.springframework.version>4.2.8.RELEASE</org.springframework.version>
		<org.springframework.ws.version>2.0.4.RELEASE</org.springframework.ws.version>
		<org.springframework.integration.version>2.1.0.RELEASE</org.springframework.integration.version>
		<org.springframework.integration.ws.version>2.1.0.PATCHED</org.springframework.integration.ws.version>
		<org.springframework.ldap-version>1.3.1.RELEASE</org.springframework.ldap-version>
		<apache.commons.codec>1.5</apache.commons.codec>
		<org.codehaus.jackson-version>1.9.4</org.codehaus.jackson-version>
		<slf4j.version>1.7.6</slf4j.version>
		<h2database.version>1.3.168</h2database.version>
		<org.apache.activemq.camel.version>5.5.0</org.apache.activemq.camel.version>
		<siteminder.version>5.5.0</siteminder.version>
		<javax.servlet.version>2.4</javax.servlet.version>
		<org.apache.activemq.camel.version>5.5.0</org.apache.activemq.camel.version>
		<org.aspectj.version>1.6.9</org.aspectj.version>
		<org.aspectj-version>${org.aspectj.version}</org.aspectj-version>
		<java-version>1.7</java-version>	
		<org.apache.cxf.version>2.6.1</org.apache.cxf.version>
		<apacheds-version>1.5.7</apacheds-version>
		<mongo-java-driver-version>3.2.2</mongo-java-driver-version>
		<spring-data-mongo-version>1.9.4.RELEASE</spring-data-mongo-version>
		<spring-data-commons-version>1.12.1.RELEASE</spring-data-commons-version>
		<org.springframework.data-jpa.version>1.5.0.RELEASE</org.springframework.data-jpa.version>
		<querydsl.version>2.9.0</querydsl.version>
		<cdi.version>2.0.Alpha4</cdi.version>
		<dal-client-version>1.0.3-SNAPSHOT</dal-client-version>
		<jackson.version>2.6.3</jackson.version>
		<jacksondatabind.version>2.6.3</jacksondatabind.version>
		<jackson-annotations-version>2.6.3</jackson-annotations-version>
		<springfox-swagger-version>2.3.0</springfox-swagger-version>
	</properties>




	<dependencyManagement>


		<dependencies>

			<!-- Mongo Spring Data JPA Libraries End -->
			<dependency>
				<groupId>org.springframework.data</groupId>
				<artifactId>spring-data-mongodb</artifactId>
				<version>${spring-data-mongo-version}</version>
			</dependency>

			<!-- mongodb java driver -->
			<dependency>
				<groupId>org.mongodb</groupId>
				<artifactId>mongo-java-driver</artifactId>
				<version>${mongo-java-driver-version}</version>
			</dependency>

			<dependency>
				<groupId>io.netty</groupId>
				<artifactId>netty-buffer</artifactId>
				<version>4.0.26.Final</version>
				<scope>compile</scope>
				<optional>true</optional>
			</dependency>
			<dependency>
				<groupId>io.netty</groupId>
				<artifactId>netty-transport</artifactId>
				<version>4.0.26.Final</version>
				<scope>compile</scope>
				<optional>true</optional>
			</dependency>
			<dependency>
				<groupId>io.netty</groupId>
				<artifactId>netty-handler</artifactId>
				<version>4.0.26.Final</version>
				<scope>compile</scope>
				<optional>true</optional>
			</dependency>
			<!--<dependency>
				<groupId>org.slf4j</groupId>
				<artifactId>slf4j-api</artifactId>
				<version>1.7.6</version>
				<scope>compile</scope>
				<optional>true</optional>
			</dependency> -->
			
			<!-- Querydsl -->
			<dependency>
				<groupId>com.mysema.querydsl</groupId>
				<artifactId>querydsl-core</artifactId>
				<version>3.6.9</version>
			</dependency>

			<dependency>
				<groupId>com.mysema.querydsl</groupId>
				<artifactId>querydsl-root</artifactId>
				<version>3.6.9</version>
			</dependency>

			<dependency>
				<groupId>com.mysema.querydsl</groupId>
				<artifactId>querydsl-mongodb</artifactId>
				<version>3.6.9</version>
			</dependency>

			<dependency>
				<groupId>com.mysema.querydsl</groupId>
				<artifactId>querydsl-apt</artifactId>
				<version>3.6.9</version>
			</dependency>

			<dependency>
				<groupId>com.mysema.querydsl</groupId>
				<artifactId>querydsl-codegen</artifactId>
				<version>3.6.9</version>
			</dependency>

			<dependency>
				<groupId>javax.annotation</groupId>
				<artifactId>jsr250-api</artifactId>
				<version>1.0</version>
				<optional>true</optional>
			</dependency>
			<!-- CDI -->
			<dependency>
				<groupId>javax.enterprise</groupId>
				<artifactId>cdi-api</artifactId>
				<version>${cdi.version}</version>
				<scope>provided</scope>
				<optional>true</optional>
			</dependency>

			<dependency>
				<groupId>javax.el</groupId>
				<artifactId>el-api</artifactId>
				<version>${cdi.version}</version>
				<scope>test</scope>
			</dependency>

			<!-- mongodb java driver ends -->

			<!-- Spring integration dependencies -->
			<dependency>
				<groupId>org.springframework.integration</groupId>
				<artifactId>spring-integration-core</artifactId>
				<version>${org.springframework.integration.version}</version>
			</dependency>
			<dependency>
				<groupId>org.springframework.integration</groupId>
				<artifactId>spring-integration-http</artifactId>
				<version>${org.springframework.integration.version}</version>
				<exclusions>
					<exclusion>
						<groupId>org.springframework</groupId>
						<artifactId>spring-webmvc</artifactId>
					</exclusion>
				</exclusions>
			</dependency>
			<dependency>
				<groupId>org.springframework.integration</groupId>
				<artifactId>spring-integration-ws</artifactId>
				<version>${org.springframework.integration.ws.version}</version>
			</dependency>
			<dependency>
				<groupId>org.springframework.integration</groupId>
				<artifactId>spring-integration-test</artifactId>
				<version>${org.springframework.integration.version}</version>
				<scope>test</scope>
			</dependency>

			<!-- Spring integration ends -->

			<!-- Spring Data commons -->
			<dependency>
				<groupId>org.springframework.data</groupId>
				<artifactId>spring-data-commons</artifactId>
				<version>${spring-data-commons-version}</version>
			</dependency>
			<dependency>
				<groupId>org.springframework</groupId>
				<artifactId>spring-webmvc</artifactId>
				<version>${org.springframework.version}</version>
			</dependency>
			<dependency>
				<groupId>org.springframework</groupId>
				<artifactId>spring-core</artifactId>
				<version>${org.springframework.version}</version>
				<exclusions>
					<exclusion>
						<groupId>commons-logging</groupId>
						<artifactId>commons-logging</artifactId>
					</exclusion>
				</exclusions>
			</dependency>
			<dependency>
				<groupId>org.springframework</groupId>
				<artifactId>spring-context</artifactId>
				<version>${org.springframework.version}</version>
				<exclusions>
					<exclusion>
						<groupId>commons-logging</groupId>
						<artifactId>commons-logging</artifactId>
					</exclusion>
				</exclusions>
			</dependency>
			<dependency>
				<groupId>org.springframework</groupId>
				<artifactId>spring-beans</artifactId>
				<version>${org.springframework.version}</version>
			</dependency>

			<dependency>
				<groupId>org.springframework.data</groupId>
				<artifactId>spring-data-jpa</artifactId>
				<version>${org.springframework.data-jpa.version}</version>
				<exclusions>
					<exclusion>
						<groupId>cglib</groupId>
						<artifactId>cglib</artifactId>
					</exclusion>
				</exclusions>
			</dependency>
			<dependency>
				<groupId>org.springframework</groupId>
				<artifactId>spring-aspects</artifactId>
				<version>${org.springframework.version}</version>
			</dependency>
			<dependency>
				<groupId>org.aspectj</groupId>
				<artifactId>aspectjrt</artifactId>
				<version>${org.aspectj.version}</version>
			</dependency>

			<dependency>
				<groupId>org.aspectj</groupId>
				<artifactId>aspectjweaver</artifactId>
				<version>${org.aspectj.version}</version>
			</dependency>



			<dependency>
				<groupId>org.hibernate</groupId>
				<artifactId>hibernate-validator</artifactId>
				<version>4.1.0.Final</version>
				<exclusions>
					<exclusion>
						<groupId>javax.xml.bind</groupId>
						<artifactId>jaxb-api</artifactId>
					</exclusion>
					<exclusion>
						<groupId>com.sun.xml.bind</groupId>
						<artifactId>jaxb-impl</artifactId>
					</exclusion>
				</exclusions>
			</dependency>

			
		</dependencies>
	</dependencyManagement>

	<build>
				
		<pluginManagement>
			<plugins>				
				<plugin>
					<artifactId>maven-compiler-plugin</artifactId>
					<version>2.3.2</version>
				</plugin>				
				
				<plugin>
					<groupId>com.mysema.maven</groupId>
					<artifactId>apt-maven-plugin</artifactId>
					<version>1.1.3</version>
					<executions>
						<execution>
							<goals>
								<goal>process</goal>
							</goals>
							<configuration>
								<outputDirectory>${project.build.directory}</outputDirectory>
								<processor>org.springframework.data.mongodb.repository.support.MongoAnnotationProcessor</processor>
								<options>
									<querydsl.entityAccessors>true</querydsl.entityAccessors>
								</options>
							</configuration>
						</execution>
					</executions>
				</plugin>
			</plugins>
		</pluginManagement>
	</build>	
	
</project>
```

---
No further details from [DATAMONGO-1512](https://jira.spring.io/browse/DATAMONGO-1512?redirect=false)

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
