### ISSUE TITLE
Spring Mongo DB 1.9.5.RELEASE | Aggregation issue by using two aggregate functions [DATAMONGO-1543]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-data-mongodb#2455]
**[Kishore Kumar Karanam](https://jira.spring.io/secure/ViewProfile.jspa?name=pandukish)** opened **[DATAMONGO-1543](https://jira.spring.io/browse/DATAMONGO-1543?redirect=false)** and commented

The below mongo DB query is working as expected in Mongo Console where as in code below exception

```javascript
db.test.aggregate(
    {
	$match : {"uniqueId":"Id1"}
    },
    {
	$group : {_id : "$hosting", total : { $sum : 1 }, amount : { $sum : "$amount" }}
    }
);
```

```
java.lang.IllegalArgumentException: Invalid reference 'amount'!
	at org.springframework.data.mongodb.core.aggregation.ExposedFieldsAggregationOperationContext.getReference(ExposedFieldsAggregationOperationContext.java:115)
	at org.springframework.data.mongodb.core.aggregation.ExposedFieldsAggregationOperationContext.getReference(ExposedFieldsAggregationOperationContext.java:68)
	at org.springframework.data.mongodb.core.aggregation.GroupOperation.toDBObject(GroupOperation.java:345)
	at org.springframework.data.mongodb.core.aggregation.Aggregation.toDbObject(Aggregation.java:331)
	at org.springframework.data.mongodb.core.MongoTemplate.aggregate(MongoTemplate.java:1521)
	at org.springframework.data.mongodb.core.MongoTemplate.aggregate(MongoTemplate.java:1462)
```

---

**Affects:** 1.9.5 (Hopper SR5)

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
