### ISSUE TITLE
Invalid reference error while using Aggregation functionality [DATAMONGO-1644]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-data-mongodb#2551]
**[Vijayakumar Velusamy](https://jira.spring.io/secure/ViewProfile.jspa?name=vkvijay)** opened **[DATAMONGO-1644](https://jira.spring.io/browse/DATAMONGO-1644?redirect=false)** and commented

I am using aggregation and lookup functions and it works fine in javascript  or mongo shell however when i use the same in program, when i use the lookup reference array in the $project then it ignore the lookup reference name

```java
Aggregation aggregation = Aggregation.newAggregation(matchbySource, unwindbenefits, matchbyBenefits,
  groupOperation, lookupOperation1, lookupOperation2, Aggregation.project().and("$_id").as("ID")
    .andInclude("groupbenefitCount").and("$rendetails").size().as("memberCount")
    .and("$renewalclient.agents").size().as("groupBrkCount"));
```

Error :

```
exception [Request processing failed; nested exception is java.lang.IllegalArgumentException: Invalid reference 'agents'!] with root cause
java.lang.IllegalArgumentException: Invalid reference 'agents'!
	at org.springframework.data.mongodb.core.aggregation.ExposedFieldsAggregationOperationContext.getReference(ExposedFieldsAggregationOperationContext.java:99)
	at org.springframework.data.mongodb.core.aggregation.ExposedFieldsAggregationOperationContext.getReference(ExposedFieldsAggregationOperationContext.java:80)
	at org.springframework.data.mongodb.core.aggregation.InheritingExposedFieldsAggregationOperationContext.resolveExposedField(InheritingExposedFieldsAggregationOperationContext.java:62)
	at org.springframework.data.mongodb.core.aggregation.ExposedFieldsAggregationOperationContext.getReference(ExposedFieldsAggregationOperationContext.java:94)
	at org.springframework.data.mongodb.core.aggregation.ExposedFieldsAggregationOperationContext.getReference(ExposedFieldsAggregationOperationContext.java:80)
	at org.springframework.data.mongodb.core.aggregation.InheritingExposedFieldsAggregationOperationContext.resolveExposedField(InheritingExposedFieldsAggregationOperationContext.java:62)
	at org.springframework.data.mongodb.core.aggregation.ExposedFieldsAggregationOperationContext.getReference(ExposedFieldsAggregationOperationContext.java:94)
	at org.springframework.data.mongodb.core.aggregation.ExposedFieldsAggregationOperationContext.getReference(ExposedFieldsAggregationOperationContext.java:80)
```

---

**Affects:** 1.9.8 (Hopper SR8)

**Reference URL:** http://stackoverflow.com/questions/42519286/spring-data-mongodb-aggregation-framework-invalid-reference

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
