### ISSUE TITLE
IllegalArgumentException: ValueType is <null> for Java-Map fallback type [DATAMONGO-1649]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-data-mongodb#2556]
**[Matthias Kappeller](https://jira.spring.io/secure/ViewProfile.jspa?name=mkappeller)** opened **[DATAMONGO-1649](https://jira.spring.io/browse/DATAMONGO-1649?redirect=false)** and commented

I attached a simple maven-project to demonstrate the problem. That's probably the best explanation of what happens.
But I'll try to explain it also by words :)

We support a repository that can be used to store a user-specific structure within a MongoDB-Document. Basically we provide a Settings-Pojo that can be extended with any other Java-Object and finally all of that can be stored in MongoDB.
But we won't store the type information within the '_class' field. In 1.10.x this simply worked. In 2.0.0.M1 it fails. (Obviously, otherwise I wouldn't write a bug report).
The key different is in [MappingMongoConverter#readMap)](https://github.com/spring-projects/spring-data-mongodb/blob/2.0.x/spring-data-mongodb/src/main/java/org/springframework/data/mongodb/core/convert/MappingMongoConverter.java#L998) and [DefaultMongoTypeMapper#getFallbackTypeFor](https://github.com/spring-projects/spring-data-mongodb/blob/2.0.x/spring-data-mongodb/src/main/java/org/springframework/data/mongodb/core/convert/DefaultMongoTypeMapper.java#L128). As there is no value type given for Map.class our code fails with:

```
java.lang.IllegalArgumentException: Target type must not be null!
	at org.springframework.util.Assert.notNull(Assert.java:134)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.readCollectionOrArray(MappingMongoConverter.java:911)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.readMap(MappingMongoConverter.java:1011)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.read(MappingMongoConverter.java:231)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.readMap(MappingMongoConverter.java:1004)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.read(MappingMongoConverter.java:231)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.readValue(MappingMongoConverter.java:1320)
```

I don't know how it should really look like? I can workaround the new behaviour by overwriting the `#getFallbackTypeFor` and use a different `ClassTypeInformation` for a `Map`.

```java
private static final Map<Document, Document> dummy = new HashMap<>();
private static final TypeInformation<?> MAP_TYPE_INFO = ClassTypeInformation.from(dummy.getClass());
```

Are we using spring-data-mongodb other than expected? Or is it indeed a bug in the 2.0.x branch?

---

**Affects:** 2.0 M1 (Kay)

**Attachments:**
- [spring-data-mongodb-mapper.zip](https://jira.spring.io/secure/attachment/23825/spring-data-mongodb-mapper.zip) (_4.62 kB_)

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
