### ISSUE TITLE
mongoTemplate.aggregate hangs, but direct dbcollection.aggregate works with exactly the same query [DATAMONGO-1722]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-data-mongodb#2630]
**[Alexey Polyakov](https://jira.spring.io/secure/ViewProfile.jspa?name=polyakov755)** opened **[DATAMONGO-1722](https://jira.spring.io/browse/DATAMONGO-1722?redirect=false)** and commented

I have a collection of locations with fields "country" and "city".
I'm trying to run a simple aggregation:

```java
MatchOperation matchOperation = new MatchOperation(Criteria.where("country").ne(null).and("city").is(null));
GroupOperation groupOperation = new GroupOperation(Fields.fields("country")).count().as("count");
Aggregation aggregation = Aggregation.newAggregation(matchOperation, groupOperation);
```

if I use `DBCollection` class, everything works fine (query runs for 100 seconds and then I get the results). the code is:

```java
AggregationOutput aggregationOutput = mongoTemplate.getCollection("ig_location").aggregate(Arrays.asList(matchOperation.toDBObject(Aggregation.DEFAULT_CONTEXT), groupOperation.toDBObject(Aggregation.DEFAULT_CONTEXT)));
```

if I try to use `MongoTemplate`, it hangs, returning no results. the code is:

```java
AggregationResults<LocationAggregationResult> aggregationResults = mongoTemplate.aggregate(aggregation, "ig_location", LocationAggregationResult.class);
```

when I check current ops on mongodb server, there's no running queries for this collection.
I retried running the code a few times and managed to get the results (but only once, all other runs result in hangs).

```
stack trace for this thread is:
"main" #1 prio=5 os_prio=31 tid=0x00007fd0da007800 nid=0x1703 runnable [0x0000700000218000]
   java.lang.Thread.State: RUNNABLE
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:170)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at com.mongodb.connection.SocketStream.read(SocketStream.java:85)
	at com.mongodb.connection.InternalStreamConnection.receiveResponseBuffers(InternalStreamConnection.java:491)
	at com.mongodb.connection.InternalStreamConnection.receiveMessage(InternalStreamConnection.java:221)
	at com.mongodb.connection.UsageTrackingInternalConnection.receiveMessage(UsageTrackingInternalConnection.java:102)
	at com.mongodb.connection.DefaultConnectionPool$PooledConnection.receiveMessage(DefaultConnectionPool.java:435)
	at com.mongodb.connection.CommandProtocol.execute(CommandProtocol.java:112)
	at com.mongodb.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:159)
	at com.mongodb.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:286)
	at com.mongodb.connection.DefaultServerConnection.command(DefaultServerConnection.java:173)
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:215)
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:186)
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:178)
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:91)
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:84)
	at com.mongodb.operation.CommandReadOperation.execute(CommandReadOperation.java:55)
	at com.mongodb.Mongo.execute(Mongo.java:772)
	at com.mongodb.Mongo$2.execute(Mongo.java:759)
	at com.mongodb.DB.executeCommand(DB.java:653)
	at com.mongodb.DB.command(DB.java:423)
	at com.mongodb.DB.command(DB.java:439)
	at org.springframework.data.mongodb.core.MongoTemplate$3.doInDB(MongoTemplate.java:391)
	at org.springframework.data.mongodb.core.MongoTemplate$3.doInDB(MongoTemplate.java:389)
	at org.springframework.data.mongodb.core.MongoTemplate.execute(MongoTemplate.java:447)
	at org.springframework.data.mongodb.core.MongoTemplate.executeCommand(MongoTemplate.java:389)
	at org.springframework.data.mongodb.core.MongoTemplate.aggregate(MongoTemplate.java:1557)
	at org.springframework.data.mongodb.core.MongoTemplate.aggregate(MongoTemplate.java:1492)
```

I expect to get the same results when running this aggregation query through `DBCollection` and through `MongoTemplate`

---

**Affects:** 1.9.10 (Hopper SR10)

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
