### ISSUE TITLE
SpEL expression in Document annotation not working [DATAMONGO-2114]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-data-mongodb#2959]
**[Fredrik Engström](https://jira.spring.io/secure/ViewProfile.jspa?name=fredrik%20engstr%C3%B6m)** opened **[DATAMONGO-2114](https://jira.spring.io/browse/DATAMONGO-2114?redirect=false)** and commented

Use case: I want to use Spel expressions to reference a bean and compute the collection name

 

Annotation:

`@Document`(collection = "#\{collectionUtil.getName()}")

 

Executing the same code with Spring Boot version 2.0.6.RELEASE works. However when switching to Spring Boot version 2.1.0.RC1 this happens:

 

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'testRepository': Invocation of init method failed; nested exception is org.springframework.expression.spel.SpelEvaluationException: EL1007E: Property or field 'collectionUtil' cannot be found on nullorg.springframework.beans.factory.BeanCreationException: Error creating bean with name 'testRepository': Invocation of init method failed; nested exception is org.springframework.expression.spel.SpelEvaluationException: EL1007E: Property or field 'collectionUtil' cannot be found on null at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1745) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE] at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:576) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE] at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:498) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE] at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE] at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE] at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE] at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE] at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:827) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE] at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:863) ~[spring-context-5.1.1.RELEASE.jar:5.1.1.RELEASE] at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546) ~[spring-context-5.1.1.RELEASE.jar:5.1.1.RELEASE] at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:771) [spring-boot-2.1.0.RC1.jar:2.1.0.RC1] at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:395) [spring-boot-2.1.0.RC1.jar:2.1.0.RC1] at org.springframework.boot.SpringApplication.run(SpringApplication.java:314) [spring-boot-2.1.0.RC1.jar:2.1.0.RC1] at org.springframework.boot.SpringApplication.run(SpringApplication.java:1256) [spring-boot-2.1.0.RC1.jar:2.1.0.RC1] at org.springframework.boot.SpringApplication.run(SpringApplication.java:1244) [spring-boot-2.1.0.RC1.jar:2.1.0.RC1] at test.mongo.TestMongoApplication.main(TestMongoApplication.java:12) [classes/:na]Caused by: org.springframework.expression.spel.SpelEvaluationException: EL1007E: Property or field 'collectionUtil' cannot be found on null at org.springframework.expression.spel.ast.PropertyOrFieldReference.readProperty(PropertyOrFieldReference.java:213) ~[spring-expression-5.1.1.RELEASE.jar:5.1.1.RELEASE] at org.springframework.expression.spel.ast.PropertyOrFieldReference.getValueInternal(PropertyOrFieldReference.java:104) ~[spring-expression-5.1.1.RELEASE.jar:5.1.1.RELEASE] at org.springframework.expression.spel.ast.PropertyOrFieldReference.getValueInternal(PropertyOrFieldReference.java:91) ~[spring-expression-5.1.1.RELEASE.jar:5.1.1.RELEASE] at org.springframework.expression.spel.ast.CompoundExpression.getValueRef(CompoundExpression.java:53) ~[spring-expression-5.1.1.RELEASE.jar:5.1.1.RELEASE] at org.springframework.expression.spel.ast.CompoundExpression.getValueInternal(CompoundExpression.java:89) ~[spring-expression-5.1.1.RELEASE.jar:5.1.1.RELEASE] at org.springframework.expression.spel.ast.SpelNodeImpl.getTypedValue(SpelNodeImpl.java:116) ~[spring-expression-5.1.1.RELEASE.jar:5.1.1.RELEASE] at org.springframework.expression.spel.standard.SpelExpression.getValue(SpelExpression.java:300) ~[spring-expression-5.1.1.RELEASE.jar:5.1.1.RELEASE] at org.springframework.data.mongodb.core.mapping.BasicMongoPersistentEntity.getCollection(BasicMongoPersistentEntity.java:97) ~[spring-data-mongodb-2.1.1.RELEASE.jar:2.1.1.RELEASE] at org.springframework.data.mongodb.core.index.MongoPersistentEntityIndexResolver.resolveIndexForEntity(MongoPersistentEntityIndexResolver.java:109) ~[spring-data-mongodb-2.1.1.RELEASE.jar:2.1.1.RELEASE] at org.springframework.data.mongodb.core.index.MongoPersistentEntityIndexResolver.resolveIndexFor(MongoPersistentEntityIndexResolver.java:90) ~[spring-data-mongodb-2.1.1.RELEASE.jar:2.1.1.RELEASE] at org.springframework.data.mongodb.core.index.MongoPersistentEntityIndexCreator.checkForAndCreateIndexes(MongoPersistentEntityIndexCreator.java:134) ~[spring-data-mongodb-2.1.1.RELEASE.jar:2.1.1.RELEASE] at org.springframework.data.mongodb.core.index.MongoPersistentEntityIndexCreator.checkForIndexes(MongoPersistentEntityIndexCreator.java:127) ~[spring-data-mongodb-2.1.1.RELEASE.jar:2.1.1.RELEASE] at org.springframework.data.mongodb.core.index.MongoPersistentEntityIndexCreator.onApplicationEvent(MongoPersistentEntityIndexCreator.java:111) ~[spring-data-mongodb-2.1.1.RELEASE.jar:2.1.1.RELEASE] at org.springframework.data.mongodb.core.index.MongoPersistentEntityIndexCreator.onApplicationEvent(MongoPersistentEntityIndexCreator.java:54) ~[spring-data-mongodb-2.1.1.RELEASE.jar:2.1.1.RELEASE] at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) ~[spring-context-5.1.1.RELEASE.jar:5.1.1.RELEASE] at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) ~[spring-context-5.1.1.RELEASE.jar:5.1.1.RELEASE] at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) ~[spring-context-5.1.1.RELEASE.jar:5.1.1.RELEASE] at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:398) ~[spring-context-5.1.1.RELEASE.jar:5.1.1.RELEASE] at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:355) ~[spring-context-5.1.1.RELEASE.jar:5.1.1.RELEASE] at org.springframework.data.mapping.context.AbstractMappingContext.addPersistentEntity(AbstractMappingContext.java:405) ~[spring-data-commons-2.1.1.RELEASE.jar:2.1.1.RELEASE] at org.springframework.data.mapping.context.AbstractMappingContext.getPersistentEntity(AbstractMappingContext.java:248) ~[spring-data-commons-2.1.1.RELEASE.jar:2.1.1.RELEASE] at org.springframework.data.mapping.context.AbstractMappingContext.getPersistentEntity(AbstractMappingContext.java:191) ~[spring-data-commons-2.1.1.RELEASE.jar:2.1.1.RELEASE] at org.springframework.data.mapping.context.AbstractMappingContext.getPersistentEntity(AbstractMappingContext.java:85) ~[spring-data-commons-2.1.1.RELEASE.jar:2.1.1.RELEASE] at org.springframework.data.mapping.context.MappingContext.getRequiredPersistentEntity(MappingContext.java:73) ~[spring-data-commons-2.1.1.RELEASE.jar:2.1.1.RELEASE] at org.springframework.data.mongodb.repository.support.MongoRepositoryFactory.getEntityInformation(MongoRepositoryFactory.java:149) ~[spring-data-mongodb-2.1.1.RELEASE.jar:2.1.1.RELEASE] at org.springframework.data.mongodb.repository.support.MongoRepositoryFactory.getTargetRepository(MongoRepositoryFactory.java:123) ~[spring-data-mongodb-2.1.1.RELEASE.jar:2.1.1.RELEASE] at org.springframework.data.repository.core.support.RepositoryFactorySupport.getRepository(RepositoryFactorySupport.java:305) ~[spring-data-commons-2.1.1.RELEASE.jar:2.1.1.RELEASE] at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.lambda$afterPropertiesSet$5(RepositoryFactoryBeanSupport.java:297) ~[spring-data-commons-2.1.1.RELEASE.jar:2.1.1.RELEASE] at org.springframework.data.util.Lazy.getNullable(Lazy.java:211) ~[spring-data-commons-2.1.1.RELEASE.jar:2.1.1.RELEASE] at org.springframework.data.util.Lazy.get(Lazy.java:94) ~[spring-data-commons-2.1.1.RELEASE.jar:2.1.1.RELEASE] at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.afterPropertiesSet(RepositoryFactoryBeanSupport.java:300) ~[spring-data-commons-2.1.1.RELEASE.jar:2.1.1.RELEASE] at org.springframework.data.mongodb.repository.support.MongoRepositoryFactoryBean.afterPropertiesSet(MongoRepositoryFactoryBean.java:119) ~[spring-data-mongodb-2.1.1.RELEASE.jar:2.1.1.RELEASE] at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1804) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE] at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1741) ~[spring-beans-5.1.1.RELEASE.jar:5.1.1.RELEASE] ... 15 common frames omitted
```

---

**Affects:** 2.1.1 (Lovelace SR1)

**Attachments:**
- [test-mongo.zip](https://jira.spring.io/secure/attachment/26066/test-mongo.zip) (_16.14 kB_)

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
