### ISSUE TITLE
Get Exception: Couldn't find PersistentEntity for type..’ when using @EnableMongoAuditing [DATAMONGO-2640]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-data-mongodb#3493]
**[Steve Jerman](https://jira.spring.io/secure/ViewProfile.jspa?name=stevejerman)** opened **[DATAMONGO-2640](https://jira.spring.io/browse/DATAMONGO-2640?redirect=false)** and commented

There are several bugs like this:
https://jira.spring.io/browse/DATAMONGO-2152
where you get an error 'java.lang.IllegalArgumentException: Couldn't find PersistentEntity for type..’ when using `@EnableMongoAuditing`

I also have run into the error and have been trying to create a standalone test case without success.

```java
java.lang.IllegalArgumentException: Couldn't find PersistentEntity for type class com.kloudspot.jamesons.datamodel.domain.rules.SmsAction!
 at org.springframework.data.mapping.context.PersistentEntities.lambda$getRequiredPersistentEntity$2(PersistentEntities.java:96)
 at java.util.Optional.orElseThrow(Optional.java:290)
 at org.springframework.data.mapping.context.PersistentEntities.getRequiredPersistentEntity(PersistentEntities.java:95)
 at org.springframework.data.auditing.IsNewAwareAuditingHandler.markAudited(IsNewAwareAuditingHandler.java:81)
 at org.springframework.data.mongodb.core.mapping.event.AuditingEntityCallback.onBeforeConvert(AuditingEntityCallback.java:54)
```

It seems to be very dependent on the order of bean creation...

Anyway I had a breakthrough this morning… I still can’t create small test case (or I would create a Jira.), but:

This works:

```java
  @Test
  public void testEight() {

   BasicMongoPersistentEntity<?> gg = mappingContexts.getPersistentEntity(SmsAction.class);
   assertThat(gg).isNotNull();

   SmsAction action = new SmsAction();
   action.setTemplateName("SMS");
   action.setType(ActionTypeEnum.sms);
   action.setContent("Stuff to send");
         atRepo.save(action);
         assertThat(atRepo.count()).isEqualTo(1);
  }
```

If I comment out the first two lines, it stops working...

Looking at IsNewAwareAuditingHandler, I see that it calls PersistentEntities.getRequiredPersistentEntity which will fail if the PersistentEntrity hasn’t already been loaded….

Any thoughts? Am I missing something?

For now, this code works as a workaround:

```java
  @Bean
  public MongoTemplate mongoTemplate(
      MongoDbFactory mongoDbFactory,
      MappingMongoConverter mappingMongoConverter,
      MongoMappingContext mappingContexts) {

    /* Hack to work around issue with Spring Data Auditing */
    Reflections reflections = new Reflections("com.kloudspot.jamesons.datamodel");

    Set<Class<? extends AbstractAuditingEntity>> subTypes =
        reflections.getSubTypesOf(AbstractAuditingEntity.class);
    for (Class<? extends AbstractAuditingEntity> clazz : subTypes) {
      mappingContexts.getPersistentEntity(clazz);
    }

    return new MongoTemplate(mongoDbFactory, mappingMongoConverter);
  }
```

---

**Affects:** 2.1.20 (Lovelace SR20), 2.2.10 (Moore SR10)

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
