### ISSUE TITLE
Caused by: org.bson.codecs.configuration.CodecConfigurationException: The uuidRepresentation has not been specified, so the UUID cannot be encoded [DATAMONGO-2660]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-data-mongodb#3513]
**[Tom Jones](https://jira.spring.io/secure/ViewProfile.jspa?name=JIRAUSER50710)** opened **[DATAMONGO-2660](https://jira.spring.io/browse/DATAMONGO-2660?redirect=false)** and commented

I'm trying to upgrade existing app from 

2.2.6.RELEASE

to 

2.3.6.RELEASE

 

Getting 

> Caused by: org.bson.codecs.configuration.CodecConfigurationException: The uuidRepresentation has not been specified, so the UUID cannot be encoded.Caused by: org.bson.codecs.configuration.CodecConfigurationException: The uuidRepresentation has not been specified, so the UUID cannot be encoded. at org.bson.codecs.UuidCodec.encode(UuidCodec.java:72) at org.bson.codecs.UuidCodec.encode(UuidCodec.java:37) at org.bson.codecs.EncoderContext.encodeWithChildContext(EncoderContext.java:91) at org.bson.codecs.DocumentCodec.writeValue(DocumentCodec.java:198) at org.bson.codecs.DocumentCodec.writeMap(DocumentCodec.java:212) at org.bson.codecs.DocumentCodec.encode(DocumentCodec.java:154) at org.bson.codecs.DocumentCodec.encode(DocumentCodec.java:45) at org.bson.codecs.BsonDocumentWrapperCodec.encode(BsonDocumentWrapperCodec.java:63) at org.bson.codecs.BsonDocumentWrapperCodec.encode(BsonDocumentWrapperCodec.java:29)

 

when running my CRUD tests for documents having UUID field.

Tried many things, nothing works, what is the right way to tell spring-boot

`}}{{@Override`
`public void configureClientSettings(MongoClientSettings.Builder builder) {`
`   builder.uuidRepresentation(UuidRepresentation.STANDARD);`
`}`

 

to use correct uuid representation. Previous version just worked, why does update break it?

---

**Affects:** 3.0.5 (Neumann SR5)

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
