### ISSUE TITLE
Aggregation annotation should be able to return a Page if you pass Pageable and Sort

### ISSUE THREAD

**Issue by mngphm** [spring-projects/spring-data-mongodb#3543]

**Comment by christophstrobl** [comment]
To serve a `Page` we'd have to do a count to get the total amount of results. This, in turn, will lead to an extended execution time and additional load on the server. 
Returning a `Slice` on the other hand might be a feasible option as this would only require to load one additional document (later truncated) to indicate if there's more data available. We'd be happy to consider a PR going that direction.

**Comment by divyajnu08** [comment]
Hi Mark ,

Can I look into this issue ? It may take some time as I have to go through the aggregation code .

Thanks

**Comment by divyajnu08** [comment]
Hi Mark

I am stuck in setup of the code at my local.
This is what I did :
Check out the spring-data-mongodb - main branch
built the jar file , created a new project with the same jar file as a dependency.

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>test</groupId>
	<artifactId>test</artifactId>
	<version>0.1</version>
	<properties>
		<java.version>15</java.version>
		<maven.compiler.source>1.8</maven.compiler.source>
 		<maven.compiler.target>1.8</maven.compiler.target>
	</properties>
	<dependencies>
		<dependency>
		    <groupId>org.springframework.data</groupId>
		    <artifactId>spring-data-mongodb</artifactId>
		    <version>3.3.0-SNAPSHOT</version>
		</dependency>
	</dependencies>
</project>

this is what i am getting as the error

Exception in thread "main" org.springframework.beans.factory.BeanDefinitionStoreException: Failed to parse configuration class [SpringConfig]; nested exception is java.io.FileNotFoundException: class path resource [org/springframework/web/servlet/config/annotation/WebMvcConfigurer.class] cannot be opened because it does not exist
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:189)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:331)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:247)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:311)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:112)

I think some more dependencies it is expecting , i tried to resolve this error but repeatedly dependencies are missing.
Can you please guide me how to setup the spring-data-mongodb project on local to make any change and test it ?
Thanks

**Comment by mp911de** [comment]
I'd suggest sticking with Java 8 for now. `WebMvcConfigurer` isn't available from Spring Data MongoDB. Going to start.spring.io and generating an application from there is a good approach to start your application with a clean Spring context bootstrap.

**Comment by divyajnu08** [comment]
Hi Mark

Currently in the code it is possible to pass a pageable with sort option in the method annotated with aggregation. Like 

@Aggregation( pipeline = {...})
public List<PersonAggregate> getPaginatedResult(Pageable page);

If we pass pageable in the method , it returns paged response.
Do we have to add an option in the aggregation annotation like 

@Aggregation( pipeline = {..} , page = 1 , sort = '$fieldName' )

or we simply have to change the code to use Slice instead of pageable in the first option ?

**Comment by mp911de** [comment]
`StringBasedAggregation` verifies currently return types and part of the ticket is to allow for paging. So yes, the check needs to be removed there.
