### ISSUE TITLE
The nonAtomic:false option is no longer allowed in the mapReduce command. Please omit or specify nonAtomic:true

### ISSUE THREAD

**Issue by vainly** [spring-projects/spring-data-mongodb#3548]
mongodb version: 4.4.2
spring-boot-starter-data-mongodb: 2.2.3.RELEASE

Hello, I'm very sorry for the delay everyone, there is a problem that has not been solved, I would like to ask everyone here。

This is my code of mongodb mapreduce 
`      String dev_no = "";
        Document queryDoc = Criteria
                    .where("dev_no").is(dev_no)
                    .and("pressure").ne(null)
                    .and("real_time").gte(begin).lte(end)
                    .getCriteriaObject();

            BasicDBObject fieldsObject = new BasicDBObject();
            fieldsObject.put("pressure", true);
            fieldsObject.put("real_time", true);

            Query query = new BasicQuery(queryDoc.toJson(), fieldsObject.toJson());
            query.with(Sort.by(new Sort.Order(Sort.Direction.ASC, "real_time")));

            String map = "function(){ emit( (this.real_time.getDate() +'-' + this.real_time.getHours()), this. pressure); }";
            String reduce = "function(key, values) { var min =  parseFloat(values[0].toJSON()['$numberDecimal']); var max =  parseFloat(values[values.length -1].toJSON()['$numberDecimal']); return max-min; }";

            MapReduceOptions options = new MapReduceOptions();
            options.outputCollection("pressure_mappreduce");
            options.outputTypeReduce();
            MapReduceResults r = mongoTemplate.mapReduce(query, MongoDBConst.IOT_COLLECTION_REALTIMERECORD, map, reduce, options, ValueObject.class);
`
This is exception of execute above code
`
com.mongodb.MongoCommandException: Command failed with error 15895 (Location15895): 'The nonAtomic:false option is no longer allowed in the mapReduce command. Please omit or specify nonAtomic:true' on server 47.95.15.240:30003. The full response is {"ok": 0.0, "errmsg": "The nonAtomic:false option is no longer allowed in the mapReduce command. Please omit or specify nonAtomic:true", "code": 15895, "codeName": "Location15895"}
	at com.mongodb.internal.connection.ProtocolHelper.getCommandFailureException(ProtocolHelper.java:175)
	at com.mongodb.internal.connection.InternalStreamConnection.receiveCommandMessageResponse(InternalStreamConnection.java:303)
	at com.mongodb.internal.connection.InternalStreamConnection.sendAndReceive(InternalStreamConnection.java:259)
	at com.mongodb.internal.connection.UsageTrackingInternalConnection.sendAndReceive(UsageTrackingInternalConnection.java:99)
	at com.mongodb.internal.connection.DefaultConnectionPool$PooledConnection.sendAndReceive(DefaultConnectionPool.java:450)
	at com.mongodb.internal.connection.CommandProtocolImpl.execute(CommandProtocolImpl.java:72)
	at com.mongodb.internal.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:218)
	at com.mongodb.internal.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:269)
	at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:131)
	at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:123)
	at com.mongodb.operation.CommandOperationHelper.executeWriteCommand(CommandOperationHelper.java:369)
	at com.mongodb.operation.CommandOperationHelper.executeWriteCommand(CommandOperationHelper.java:360)
	at com.mongodb.operation.CommandOperationHelper.executeCommand(CommandOperationHelper.java:284)
	at com.mongodb.operation.CommandOperationHelper.executeCommand(CommandOperationHelper.java:277)
	at com.mongodb.operation.MapReduceToCollectionOperation$1.call(MapReduceToCollectionOperation.java:516)
	at com.mongodb.operation.MapReduceToCollectionOperation$1.call(MapReduceToCollectionOperation.java:512)
	at com.mongodb.operation.OperationHelper.withConnectionSource(OperationHelper.java:530)
	at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:492)
	at com.mongodb.operation.MapReduceToCollectionOperation.execute(MapReduceToCollectionOperation.java:512)
	at com.mongodb.operation.MapReduceToCollectionOperation.execute(MapReduceToCollectionOperation.java:72)
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:206)
	at com.mongodb.client.internal.MapReduceIterableImpl.asReadOperation(MapReduceIterableImpl.java:205)
	at com.mongodb.client.internal.MongoIterableImpl.execute(MongoIterableImpl.java:143)
	at com.mongodb.client.internal.MongoIterableImpl.iterator(MongoIterableImpl.java:92)
	at org.springframework.data.mongodb.core.MongoTemplate.mapReduce(MongoTemplate.java:1936)
	at org.springframework.data.mongodb.core.MongoTemplate.mapReduce(MongoTemplate.java:1841)
`
The nonAtomic is not property of MapReduceOptions and can't set value, how can I solve this exception?

**Comment by christophstrobl** [comment]
Just saw that the fix was also ported to the [3.12.x](https://github.com/mongodb/mongo-java-driver/commit/a97d7d8acb3afdfaf8f92bd4f8d71157f32dbdb4) driver which is compatible with the version of _Spring Data & Boot_ you are using. Maybe upgrading the driver to `3.12.4` would be the easiest solution.

**Comment by vainly** [comment]
@christophstrobl Thank you very much, I solved the problem after upgrading the driver.

**Comment by christophstrobl** [comment]
@vainly thanks for the feedback. Glad it works for you now!
