### ISSUE TITLE
Criteria object not allowing to use field names with underscore in them

### ISSUE THREAD

**Issue by SubashL** [spring-projects/spring-data-mongodb#3601]
Hi,

Our current Spring Data MongoDB version is 2.0.5.RELEASE.

We are migrating to 3.1.5.

Below is the query we use to retrieve the data from the database

@Autowired
private MongoOperations mongoOperation;

query.addCriteria(Criteria.where("business_area").is(buName)
                .andOperator(Criteria.where("onboard_status").exists(true)
                .andOperator(Criteria.where("onboard_status").is("approve"))));

mongoOperation.find(query, ABC.class, "abc");

and these are the imports we use for the above classes.

import org.springframework.data.mongodb.core.MongoOperations;
import org.springframework.data.mongodb.core.query.Criteria;
import org.springframework.data.mongodb.core.query.Query;

In 2.0.5.RELEASE this used to be working fine. We get the desired data. But in 3.1.5. version, we are getting the below error.

**org.springframework.data.mapping.PropertyReferenceException: No property onboard found for type FluidApplication!**

Below is the POJO definition for the above data.

`public class FluidApplication {

    @Id
    @JsonSerialize(using = ToStringSerializer.class)
    private ObjectId id;
    private String requestor_name;
    private String requestor_email;
    private String business_area;
    private String onboard_status;
    private String appType;

    private String application_name;
    private String application_type;
    private String business_functionality;
    private String service_critically;
    private String business_impact;
    private String golivedate;
} `

**Please let us know how to solve this issue. We cannot use @Column annotation above the fields as we have more fields of this kind in other collections and please let us know whether something has changed from 2.0.5.RELEASE to 3.1.5.**

**Comment by SubashL** [comment]
Please assist us in solving the issue. this is blocking our project. We like to know what have changed wrt underscore usage in field names from 2.0.5.RELEASE and 3.1.5

**Comment by SubashL** [comment]
@christophstrobl please let us know if you need any information from us. Could you please let us know what does it mean by type: regression.

**Comment by christophstrobl** [comment]
Can you please provide the full stack trace and context within which the error occurs. Preferable a [Minimal Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) that demonstrates the issue.

I've been looking current _main_ branch and the mentioned _3.1.5_ release and the following works just fine on both.
```
@Test
void criteriaUsingPropertiesWithUnderscores() {

	WithUnderscoreProperties source = new WithUnderscoreProperties();
	source.id = "id-1";
	source.requestor_name = "req-name";
	source.requestor_email= "req-email";
	
	template.save(source);
	
	Query query = query(where("requestor_name").is("req-name").andOperator(where("requestor_email").is("req-email")));
	assertThat(template.findOne(query, WithUnderscoreProperties.class)).isEqualTo(source);
}

class WithUnderscoreProperties {

	@Id String id;
	
	private String requestor_name;
	private String requestor_email;

       // getter / setters
}
```

**Comment by SubashL** [comment]
@christophstrobl thanks a lot for the reply.

```
org.springframework.data.mapping.PropertyReferenceException: No property provider found for type SimpleDocument!

	at org.springframework.data.mapping.PropertyPath.<init>(PropertyPath.java:90)
	at org.springframework.data.mapping.PropertyPath.create(PropertyPath.java:437)
	at org.springframework.data.mapping.PropertyPath.create(PropertyPath.java:413)
	at org.springframework.data.mapping.PropertyPath.lambda$from$0(PropertyPath.java:366)
	at java.base/java.util.concurrent.ConcurrentMap.computeIfAbsent(ConcurrentMap.java:330)
	at org.springframework.data.mapping.PropertyPath.from(PropertyPath.java:348)
	at org.springframework.data.mongodb.core.convert.QueryMapper$MetadataBackedField.getPath(QueryMapper.java:1090)
	at org.springframework.data.mongodb.core.convert.QueryMapper$MetadataBackedField.<init>(QueryMapper.java:968)
	at org.springframework.data.mongodb.core.convert.QueryMapper$MetadataBackedField.with(QueryMapper.java:979)
	at org.springframework.data.mongodb.core.convert.QueryMapper$MetadataBackedField.with(QueryMapper.java:923)
	at org.springframework.data.mongodb.core.convert.QueryMapper.getMappedKeyword(QueryMapper.java:314)
	at org.springframework.data.mongodb.core.convert.QueryMapper.getMappedObjectForField(QueryMapper.java:238)
	at org.springframework.data.mongodb.core.convert.QueryMapper.getMappedObject(QueryMapper.java:143)
	at org.springframework.data.mongodb.core.QueryOperations$QueryContext.getMappedQuery(QueryOperations.java:255)
	at org.springframework.data.mongodb.core.MongoTemplate.doFind(MongoTemplate.java:2518)
	at org.springframework.data.mongodb.core.MongoTemplate.doFind(MongoTemplate.java:2507)
	at org.springframework.data.mongodb.core.MongoTemplate.find(MongoTemplate.java:850)
	at com.javasampleapproach.mongodb.SimpleDao.getPendingSubscriberApprovalsForMultipleBu(SimpleDao.java:32)
	at com.javasampleapproach.mongodb.SimpleDao$$FastClassBySpringCGLIB$$be9914b7.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692)
	at com.javasampleapproach.mongodb.SimpleDao$$EnhancerBySpringCGLIB$$6776f26a.getPendingSubscriberApprovalsForMultipleBu(<generated>)
	at com.javasampleapproach.mongodb.SpringbootMongoDbApplicationTests_3_1_5.getObjectInClause(SpringbootMongoDbApplicationTests_3_1_5.java:50)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:688)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:210)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:206)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:131)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:65)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:75)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:71)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53)



```

this is the complete stacktrace of the issue

**Comment by SubashL** [comment]
Please find the sample MRE and let me know if you need further information.

[SpringBoot-MongoDb.zip](https://github.com/spring-projects/spring-data-mongodb/files/6190628/SpringBoot-MongoDb.zip)

there are two test case files one for 2.0.5.RELEASE and another for 3.1.5.

just update the version in pom.xml before executing particular version testcase

removed our mongo creds.

**Comment by SubashL** [comment]
What we have found after running few tests is the issue is only for clauses other than **is**

like **in and exists**

**Comment by christophstrobl** [comment]
thanks for the update - will give it another spin

**Comment by SubashL** [comment]
Our Mongo db version is 4.0.19

**Comment by SubashL** [comment]
@christophstrobl could you please let us know the updates on this issue.

**Comment by SubashL** [comment]
@christophstrobl  could you please let us know the updates on this issue.

**Comment by christophstrobl** [comment]
There's an open PR (#3607) - though this issue might see a broader fix in data-commons.

**Comment by SubashL** [comment]
So for time being, if this PR is accepted and merged, can I use the latest version of spring data mongo which should allow me in working with fields having underscores?

**Comment by SubashL** [comment]
@christophstrobl Please let us know when can we expect the pull request to be merged. Once merged, what version should I use to get the latest.

**Comment by SubashL** [comment]
@christophstrobl Please let us know the update on when can we use this functionality. We are currently blocked in our release.

**Comment by SubashL** [comment]
@christophstrobl @mp911de could you please update on this issue.

**Comment by SubashL** [comment]
@christophstrobl @mp911de Please update us on the issue

**Comment by mp911de** [comment]
Follow-up: #3620
