### ISSUE TITLE
[3.2.0-M5] InaccessibleObjectException with GridFS after upgrading to OpenJDK 16

### ISSUE THREAD

**Issue by juergenzimmermann** [spring-projects/spring-data-mongodb#3610]
After upgrading from OpenJDK 15.0.2 to OpenJDK 16 I get an _InaccessibleObjectException_ (see stacktrace below) when I invoke `ReactiveGridFsOperations.store(Publisher<DataBuffer> content, @Nullable String filename, @Nullable Object metadata)`.

```
2021-03-25T21:40:06,592 ERROR[nioEventLoopGroup-2-9] o.s.b.a.w.r.e.AbstractErrorWebExceptionHandler: [4cfccb4]  500 Server Error for HTTP PATCH "/api/00000000-0000-0000-0000-000000000001"
java.lang.reflect.InaccessibleObjectException: Unable to make protected java.nio.charset.Charset(java.lang.String,java.lang.String[]) accessible: module java.base does not "opens java.nio.charset" to unnamed module @7f552bd3
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	|_ checkpoint ⇢ org.springframework.web.filter.reactive.ServerWebExchangeContextFilter [DefaultWebFilterChain]
	|_ checkpoint ⇢ org.springframework.security.web.server.authorization.AuthorizationWebFilter [DefaultWebFilterChain]
	|_ checkpoint ⇢ org.springframework.security.web.server.authorization.ExceptionTranslationWebFilter [DefaultWebFilterChain]
	|_ checkpoint ⇢ org.springframework.security.web.server.authentication.logout.LogoutWebFilter [DefaultWebFilterChain]
	|_ checkpoint ⇢ org.springframework.security.web.server.savedrequest.ServerRequestCacheWebFilter [DefaultWebFilterChain]
	|_ checkpoint ⇢ org.springframework.security.web.server.context.SecurityContextServerWebExchangeWebFilter [DefaultWebFilterChain]
	|_ checkpoint ⇢ org.springframework.security.web.server.authentication.AuthenticationWebFilter [DefaultWebFilterChain]
	|_ checkpoint ⇢ org.springframework.security.web.server.context.ReactorContextWebFilter [DefaultWebFilterChain]
	|_ checkpoint ⇢ org.springframework.security.web.server.header.HttpHeaderWriterWebFilter [DefaultWebFilterChain]
	|_ checkpoint ⇢ org.springframework.security.config.web.server.ServerHttpSecurity$ServerWebExchangeReactorContextWebFilter [DefaultWebFilterChain]
	|_ checkpoint ⇢ org.springframework.security.web.server.WebFilterChainProxy [DefaultWebFilterChain]
	|_ checkpoint ⇢ org.springframework.boot.actuate.metrics.web.reactive.server.MetricsWebFilter [DefaultWebFilterChain]
	|_ checkpoint ⇢ HTTP PATCH "/api/00000000-0000-0000-0000-000000000001" [ExceptionHandlingWebHandler]
Stack trace:
		at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
		at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
		at java.base/java.lang.reflect.Constructor.checkCanSetAccessible(Constructor.java:188)
		at java.base/java.lang.reflect.Constructor.setAccessible(Constructor.java:181)
		at org.springframework.util.ReflectionUtils.makeAccessible(ReflectionUtils.java:202)
		at org.springframework.data.mapping.PreferredConstructor.<init>(PreferredConstructor.java:63)
		at org.springframework.data.mapping.model.PreferredConstructorDiscoverer$Discoverers.buildPreferredConstructor(PreferredConstructorDiscoverer.java:222)
		at org.springframework.data.mapping.model.PreferredConstructorDiscoverer$Discoverers.access$200(PreferredConstructorDiscoverer.java:91)
		at org.springframework.data.mapping.model.PreferredConstructorDiscoverer$Discoverers$1.discover(PreferredConstructorDiscoverer.java:134)
		at org.springframework.data.mapping.model.PreferredConstructorDiscoverer.discover(PreferredConstructorDiscoverer.java:79)
		at org.springframework.data.mapping.model.BasicPersistentEntity.<init>(BasicPersistentEntity.java:112)
		at org.springframework.data.mongodb.core.mapping.BasicMongoPersistentEntity.<init>(BasicMongoPersistentEntity.java:77)
		at org.springframework.data.mongodb.core.mapping.MongoMappingContext.createPersistentEntity(MongoMappingContext.java:91)
		at org.springframework.data.mongodb.core.mapping.MongoMappingContext.createPersistentEntity(MongoMappingContext.java:40)
		at org.springframework.data.mapping.context.AbstractMappingContext.addPersistentEntity(AbstractMappingContext.java:367)
		at java.base/java.util.Collections$SingletonSet.forEach(Collections.java:4872)
		at org.springframework.data.mapping.context.AbstractMappingContext$PersistentPropertyCreator.createAndRegisterProperty(AbstractMappingContext.java:563)
		at org.springframework.data.mapping.context.AbstractMappingContext$PersistentPropertyCreator.doWith(AbstractMappingContext.java:521)
		at org.springframework.util.ReflectionUtils.doWithFields(ReflectionUtils.java:710)
		at org.springframework.data.mapping.context.AbstractMappingContext.addPersistentEntity(AbstractMappingContext.java:384)
		at org.springframework.data.mapping.context.AbstractMappingContext.getPersistentEntity(AbstractMappingContext.java:258)
		at org.springframework.data.mapping.context.AbstractMappingContext.getPersistentEntity(AbstractMappingContext.java:201)
		at org.springframework.data.mapping.context.AbstractMappingContext.getPersistentEntity(AbstractMappingContext.java:87)
		at org.springframework.data.mapping.context.MappingContext.getRequiredPersistentEntity(MappingContext.java:73)
		at org.springframework.data.mongodb.core.convert.MappingMongoConverter.writeInternal(MappingMongoConverter.java:606)
		at org.springframework.data.mongodb.core.convert.MappingMongoConverter.write(MappingMongoConverter.java:557)
		at org.springframework.data.mongodb.core.convert.MappingMongoConverter.write(MappingMongoConverter.java:101)
		at org.springframework.data.mongodb.gridfs.GridFsOperationsSupport.toDocument(GridFsOperationsSupport.java:100)
		at org.springframework.data.mongodb.gridfs.ReactiveGridFsTemplate.store(ReactiveGridFsTemplate.java:121)
		at org.springframework.data.mongodb.gridfs.ReactiveGridFsOperations.store(ReactiveGridFsOperations.java:103)
		at com.acme.kunde.service.KundeFileService.save$suspendImpl(KundeFileService.kt:95)
		at com.acme.kunde.service.KundeFileService$save$1.invokeSuspend(KundeFileService.kt)
		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
		at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:234)
		at kotlinx.coroutines.DispatchedTaskKt.resumeUnconfined(DispatchedTask.kt:190)
		at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:161)
		at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:369)
		at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:403)
		at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:395)
		at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:300)
		at kotlinx.coroutines.reactive.AwaitKt$awaitOne$$inlined$suspendCancellableCoroutine$lambda$1.onComplete(Await.kt:178)
		at reactor.core.publisher.StrictSubscriber.onComplete(StrictSubscriber.java:123)
		at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onComplete(FluxContextWrite.java:126)
		at reactor.core.publisher.MonoIgnoreElements$IgnoreElementsSubscriber.onComplete(MonoIgnoreElements.java:88)
		at reactor.core.publisher.FluxFlatMap$FlatMapMain.checkTerminated(FluxFlatMap.java:846)
		at reactor.core.publisher.FluxFlatMap$FlatMapMain.drainLoop(FluxFlatMap.java:608)
		at reactor.core.publisher.FluxFlatMap$FlatMapMain.drain(FluxFlatMap.java:588)
		at reactor.core.publisher.FluxFlatMap$FlatMapMain.onComplete(FluxFlatMap.java:465)
		at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onComplete(MonoFlatMapMany.java:260)
		at reactor.core.publisher.FluxCreate$BaseSink.complete(FluxCreate.java:439)
		at reactor.core.publisher.FluxCreate$BufferAsyncSink.drain(FluxCreate.java:784)
		at reactor.core.publisher.FluxCreate$BufferAsyncSink.complete(FluxCreate.java:732)
		at reactor.core.publisher.FluxCreate$SerializedFluxSink.drainLoop(FluxCreate.java:240)
		at reactor.core.publisher.FluxCreate$SerializedFluxSink.drain(FluxCreate.java:206)
		at reactor.core.publisher.FluxCreate$SerializedFluxSink.complete(FluxCreate.java:197)
		at com.mongodb.reactivestreams.client.internal.BatchCursorFlux.lambda$recurseCursor$4(BatchCursorFlux.java:98)
		at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onComplete(MonoPeekTerminal.java:289)
		at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onComplete(MonoPeekTerminal.java:299)
		at reactor.core.publisher.FluxPeekFuseable$PeekConditionalSubscriber.onComplete(FluxPeekFuseable.java:940)
		at reactor.core.publisher.MonoCreate$DefaultMonoSink.success(MonoCreate.java:133)
		at com.mongodb.reactivestreams.client.internal.MongoOperationPublisher.lambda$sinkToCallback$30(MongoOperationPublisher.java:548)
		at com.mongodb.internal.operation.AsyncQueryBatchCursor.next(AsyncQueryBatchCursor.java:213)
		at com.mongodb.internal.operation.AsyncQueryBatchCursor.next(AsyncQueryBatchCursor.java:138)
		at com.mongodb.reactivestreams.client.internal.BatchCursor.lambda$next$0(BatchCursor.java:35)
		at reactor.core.publisher.MonoCreate.subscribe(MonoCreate.java:57)
		at reactor.core.publisher.Mono.subscribe(Mono.java:4099)
		at reactor.core.publisher.Mono.subscribeWith(Mono.java:4214)
		at reactor.core.publisher.Mono.subscribe(Mono.java:3931)
		at com.mongodb.reactivestreams.client.internal.BatchCursorFlux.recurseCursor(BatchCursorFlux.java:104)
		at com.mongodb.reactivestreams.client.internal.BatchCursorFlux.lambda$subscribe$0(BatchCursorFlux.java:56)
		at reactor.core.publisher.LambdaMonoSubscriber.onNext(LambdaMonoSubscriber.java:171)
		at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:127)
		at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1815)
		at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:249)
		at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onNext(MonoPeekTerminal.java:180)
		at reactor.core.publisher.MonoCreate$DefaultMonoSink.success(MonoCreate.java:160)
		at com.mongodb.reactivestreams.client.internal.MongoOperationPublisher.lambda$sinkToCallback$30(MongoOperationPublisher.java:550)
		at com.mongodb.reactivestreams.client.internal.OperationExecutorImpl.lambda$execute$2(OperationExecutorImpl.java:73)
		at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:48)
		at com.mongodb.internal.operation.FindOperation$3.onResult(FindOperation.java:755)
		at com.mongodb.internal.operation.OperationHelper$ReferenceCountedReleasingWrappedCallback.onResult(OperationHelper.java:532)
		at com.mongodb.internal.operation.CommandOperationHelper$10.onResult(CommandOperationHelper.java:483)
		at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:48)
		at com.mongodb.internal.connection.DefaultServer$DefaultServerProtocolExecutor$2.onResult(DefaultServer.java:286)
		at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:48)
		at com.mongodb.internal.connection.CommandProtocolImpl$1.onResult(CommandProtocolImpl.java:84)
		at com.mongodb.internal.connection.DefaultConnectionPool$PooledConnection$2.onResult(DefaultConnectionPool.java:530)
		at com.mongodb.internal.connection.UsageTrackingInternalConnection$2.onResult(UsageTrackingInternalConnection.java:142)
		at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:48)
		at com.mongodb.internal.connection.InternalStreamConnection$2$1.onResult(InternalStreamConnection.java:462)
		at com.mongodb.internal.connection.InternalStreamConnection$2$1.onResult(InternalStreamConnection.java:439)
		at com.mongodb.internal.connection.InternalStreamConnection$MessageHeaderCallback$MessageCallback.onResult(InternalStreamConnection.java:744)
		at com.mongodb.internal.connection.InternalStreamConnection$MessageHeaderCallback$MessageCallback.onResult(InternalStreamConnection.java:711)
		at com.mongodb.internal.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:581)
		at com.mongodb.internal.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:578)
		at com.mongodb.connection.netty.NettyStream.readAsync(NettyStream.java:322)
		at com.mongodb.connection.netty.NettyStream.readAsync(NettyStream.java:269)
		at com.mongodb.internal.connection.InternalStreamConnection.readAsync(InternalStreamConnection.java:578)
		at com.mongodb.internal.connection.InternalStreamConnection.access$1100(InternalStreamConnection.java:78)
		at com.mongodb.internal.connection.InternalStreamConnection$MessageHeaderCallback.onResult(InternalStreamConnection.java:701)
		at com.mongodb.internal.connection.InternalStreamConnection$MessageHeaderCallback.onResult(InternalStreamConnection.java:686)
		at com.mongodb.internal.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:581)
		at com.mongodb.internal.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:578)
		at com.mongodb.connection.netty.NettyStream.readAsync(NettyStream.java:322)
		at com.mongodb.connection.netty.NettyStream.handleReadResponse(NettyStream.java:350)
		at com.mongodb.connection.netty.NettyStream.access$1200(NettyStream.java:104)
		at com.mongodb.connection.netty.NettyStream$InboundBufferHandler.channelRead0(NettyStream.java:409)
		at com.mongodb.connection.netty.NettyStream$InboundBufferHandler.channelRead0(NettyStream.java:406)
```

**Comment by odrotbohm** [comment]
What does the type you hand in for the metadata look like? Seems the object mapping runs into a `Charset` and the analysis of its constructor fails.

**Comment by juergenzimmermann** [comment]
`filename` as the 2nd argument is a String object, `metadata` as the 3rd argument is a `MediaType` object for `image/png`.

**Comment by odrotbohm** [comment]
Shouldn't the very latter be some kind of document/map? I guess you can work around this for now by flattening the `MediaType` instance into a `String` and parsing it back on reading. We're gonna discuss this during the triage call on Monday. Adding a `Converter` implementation to translate between `MediaType` and `String` (and back) automatically seems to make sense here.

**Comment by juergenzimmermann** [comment]
@odrotbohm Providing `@WritingConverter` and `@ReadingConverter` as `MongoCustomConversions` between `MediaType` and `String` didn't help: same exception and same stacktrace.

**Comment by juergenzimmermann** [comment]
@odrotbohm  Using `store(dataBuffers, filename, "${mediaType.type}/${mediaType.subtype}")` instead of `store(dataBuffers, filename, mediaType)` works. I'd recommend to also privide an overloaded method `default Mono<ObjectId> store(Publisher<DataBuffer> content, @Nullable String filename, @Nullable MediaType contentType)` in `ReactiveGridFsOperations`.

**Comment by mp911de** [comment]
`MediaType` a Spring Web type. We have already a few `store` overloads including `store(Publisher<DataBuffer> content, @Nullable String filename, @Nullable String contentType)`. Adding another series of overloads rather clutters the API.

I'd rather refrain from using `MediaType` as metadata since the upload API has a well-defined `contentType` (`ReactiveGridFsUploadBuilder.contentType(String contentType)` method.

**Comment by juergenzimmermann** [comment]
OK, got it.
