### ISSUE TITLE
Mongo 4.4 support, query doesn't work

### ISSUE THREAD

**Issue by ceyhunn** [spring-projects/spring-data-mongodb#3618]
public class Item {
  private int itemProperty;
  ....
}
String search="20";
Query query = new Query();
cr = Criteria.where("$where").is("/^" + search + ".*/.test(this.itemProperty)");
query.addCriteria(cr);
mongoTemplate.find(query, Item.class);

This query works with mongo version 4.2.1, but with version 4.4.1 it gives following error:
```
Caused by: org.springframework.data.mongodb.UncategorizedMongoDbException: Query failed with error code 2 and error message '$where is not allowed in this context' on server .....; nested exception is com.mongodb.MongoQueryException: Query failed with error code 2 and error message '$where is not allowed in this context' on server ....
	at org.springframework.data.mongodb.core.MongoExceptionTranslator.translateExceptionIfPossible(MongoExceptionTranslator.java:133) ~[spring-data-mongodb-3.1.5.jar:3.1.5]
	at org.springframework.data.mongodb.core.MongoTemplate.potentiallyConvertRuntimeException(MongoTemplate.java:2881) ~[spring-data-mongodb-3.1.5.jar:3.1.5]
	at org.springframework.data.mongodb.core.MongoTemplate.executeFindMultiInternal(MongoTemplate.java:2806) ~[spring-data-mongodb-3.1.5.jar:3.1.5]
	at org.springframework.data.mongodb.core.MongoTemplate.doFind(MongoTemplate.java:2525) ~[spring-data-mongodb-3.1.5.jar:3.1.5]
	at org.springframework.data.mongodb.core.MongoTemplate.doFind(MongoTemplate.java:2507) ~[spring-data-mongodb-3.1.5.jar:3.1.5]
	at org.springframework.data.mongodb.core.MongoTemplate.find(MongoTemplate.java:850) ~[spring-data-mongodb-3.1.5.jar:3.1.5]
	at org.springframework.data.mongodb.core.MongoTemplate.find(MongoTemplate.java:836) ~[spring-data-mongodb-3.1.5.jar:3.1.5]  
```

**Comment by christophstrobl** [comment]
The behavior of `$where` changed in MongoDB 4.4.
It is also recommended and to use `new BasicQuery("{ '$where' : '...'} ")` for native query expressions like this.


Going forward we'll be supporting `$expr` via `Query` (see: #3587).

**Comment by ceyhunn** [comment]
Hi @christophstrobl , 

> It is also recommended to use `new BasicQuery("{ '$where' : '...'} ")` for native query expressions like this.

This also doesn't work. Same error.

**Comment by christophstrobl** [comment]
I checked the issue again and everything seems to work as expected when running against MongoDB server versions `4.4.4` and `5.0.0`

**Comment by ceyhunn** [comment]
> I checked the issue again and everything seems to work as expected when running against MongoDB server versions `4.4.4` and `5.0.0`

Thank you very much.
