### ISSUE TITLE
NPE in QueryMapper when use Query with `null` as value

### ISSUE THREAD

**Issue by EGD** [spring-projects/spring-data-mongodb#3633]
Spring Data MongoDB version: 3.1.5

used Query annotation:
```java
@Query("parentId: null")
AnyEntity findRootScope();
```
used entity class:
```public class AnyEntity {
    @Id
    public String id;
    public String name;
    @Field(targetType = FieldType.OBJECT_ID)
    public String parentId;
}
```

when calling this method i get NullPointerException:
> java.lang.NullPointerException
	at org.springframework.data.mongodb.core.convert.QueryMapper.applyFieldTargetTypeHintToValue(QueryMapper.java:692)
	at org.springframework.data.mongodb.core.convert.QueryMapper.getMappedValue(QueryMapper.java:335)
	at org.springframework.data.mongodb.core.convert.QueryMapper.getMappedObjectForField(QueryMapper.java:240)
	at org.springframework.data.mongodb.core.convert.QueryMapper.getMappedObject(QueryMapper.java:143)
	at org.springframework.data.mongodb.core.QueryOperations$QueryContext.getMappedQuery(QueryOperations.java:255)
	at org.springframework.data.mongodb.core.MongoTemplate.doFind(MongoTemplate.java:2542)
	at org.springframework.data.mongodb.core.ExecutableFindOperationSupport$ExecutableFindSupport.doFind(ExecutableFindOperationSupport.java:220)
	at org.springframework.data.mongodb.core.ExecutableFindOperationSupport$ExecutableFindSupport.oneValue(ExecutableFindOperationSupport.java:132)
	at org.springframework.data.mongodb.repository.query.AbstractMongoQuery.lambda$getExecution$4(AbstractMongoQuery.java:159)
	at org.springframework.data.mongodb.repository.query.AbstractMongoQuery.doExecute(AbstractMongoQuery.java:132)
	at org.springframework.data.mongodb.repository.query.AbstractMongoQuery.execute(AbstractMongoQuery.java:107)
	at org.springframework.data.repository.core.support.RepositoryMethodInvoker.doInvoke(RepositoryMethodInvoker.java:137)
	at org.springframework.data.repository.core.support.RepositoryMethodInvoker.invoke(RepositoryMethodInvoker.java:121)
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.doInvoke(QueryExecutorMethodInterceptor.java:152)
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.invoke(QueryExecutorMethodInterceptor.java:131)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215)
	at com.sun.proxy.$Proxy44.findRootScope(Unknown Source)

**Comment by christophstrobl** [comment]
Thanks for reporting - well look into it.
Meanwhile, have you tried `{ parentId : { $exists: false } }` or is an equality filter required here?

**Comment by EGD** [comment]
Thanks, in my particular case, replacing to `$exists` works.

**Comment by rogeriomgatto** [comment]
Another workaround is to use `new BsonNull()` instead of `null`. This also works for setting `null` values in update dsl, which triggers the same bug.
