### ISSUE TITLE
Instantiation of CustomConversions fails when a given Converter instances is created via anonymous lambda expression in Kotlin 1.5.0

### ISSUE THREAD

**Issue by VTLob** [spring-projects/spring-data-mongodb#3665]
**Given:**
* a Spring-Boot project
* using Spring-Data-MongoDB
* using Kotlin 1.5.0

**When:**
* there is a MongoCustomConversions bean
* which gets constructed via a list of Converter
* where at least one of the converters is initialized as an anonymous object via lambda expression

**Then:**
* application startup fails with error `Couldn't resolve type arguments for class path.to.configuration.class$$Lambda$[...]!`.

**Any of the following alterations will avoid the error:**
* initializing the converter via object expression
* using Kotlin 1.4.0

I cannot say if this is an issue of Spring-Data-MongoDB, Spring-Core, Kotlin or any combination of those. Also since a workaround exists there is no urgency from our side.

**Minimal example project:** https://github.com/VTLob/spring-mongodb-converter-kotlin-issue

**Additional information:**

Example of non-working anonymous lambda expression:
```kotlin
Converter<Decimal128, BigDecimal> { source -> BigDecimal(source.toString()) }
```
Example of working anonymous object expression:
```kotlin
object : Converter<Decimal128, BigDecimal> {
    override fun convert(source: Decimal128) = BigDecimal(source.toString())
}
```

Full stacktrace:
```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mongoCustomConversions' defined in de.vtlob.spring.mongodb.converter.kotlin.issue.ExampleApplication: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.data.mongodb.core.convert.MongoCustomConversions]: Factory method 'mongoCustomConversions' threw exception; nested exception is java.lang.IllegalStateException: Couldn't resolve type arguments for class de.vtlob.spring.mongodb.converter.kotlin.issue.ExampleApplication$$Lambda$382/0x00000008002eb440!
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:658) ~[spring-beans-5.3.7.jar:5.3.7]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:486) ~[spring-beans-5.3.7.jar:5.3.7]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1334) ~[spring-beans-5.3.7.jar:5.3.7]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1177) ~[spring-beans-5.3.7.jar:5.3.7]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:564) ~[spring-beans-5.3.7.jar:5.3.7]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524) ~[spring-beans-5.3.7.jar:5.3.7]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.7.jar:5.3.7]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.7.jar:5.3.7]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.7.jar:5.3.7]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.7.jar:5.3.7]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944) ~[spring-beans-5.3.7.jar:5.3.7]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[spring-context-5.3.7.jar:5.3.7]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[spring-context-5.3.7.jar:5.3.7]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758) ~[spring-boot-2.5.0.jar:2.5.0]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:438) ~[spring-boot-2.5.0.jar:2.5.0]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:337) ~[spring-boot-2.5.0.jar:2.5.0]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1336) ~[spring-boot-2.5.0.jar:2.5.0]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1325) ~[spring-boot-2.5.0.jar:2.5.0]
	at de.vtlob.spring.mongodb.converter.kotlin.issue.ExampleApplicationKt.main(ExampleApplication.kt:30) ~[classes/:na]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.data.mongodb.core.convert.MongoCustomConversions]: Factory method 'mongoCustomConversions' threw exception; nested exception is java.lang.IllegalStateException: Couldn't resolve type arguments for class de.vtlob.spring.mongodb.converter.kotlin.issue.ExampleApplication$$Lambda$382/0x00000008002eb440!
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185) ~[spring-beans-5.3.7.jar:5.3.7]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653) ~[spring-beans-5.3.7.jar:5.3.7]
	... 18 common frames omitted
Caused by: java.lang.IllegalStateException: Couldn't resolve type arguments for class de.vtlob.spring.mongodb.converter.kotlin.issue.ExampleApplication$$Lambda$382/0x00000008002eb440!
	at org.springframework.data.convert.CustomConversions$StoreConversions.getRegistrationFor(CustomConversions.java:796) ~[spring-data-commons-2.5.1.jar:2.5.1]
	at org.springframework.data.convert.CustomConversions$StoreConversions.getRegistrationsFor(CustomConversions.java:782) ~[spring-data-commons-2.5.1.jar:2.5.1]
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[na:na]
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497) ~[na:na]
	at org.springframework.data.convert.CustomConversions.collectPotentialConverterRegistrations(CustomConversions.java:196) ~[spring-data-commons-2.5.1.jar:2.5.1]
	at org.springframework.data.convert.CustomConversions.<init>(CustomConversions.java:114) ~[spring-data-commons-2.5.1.jar:2.5.1]
	at org.springframework.data.mongodb.core.convert.MongoCustomConversions.<init>(MongoCustomConversions.java:98) ~[spring-data-mongodb-3.2.1.jar:3.2.1]
	at org.springframework.data.mongodb.core.convert.MongoCustomConversions.<init>(MongoCustomConversions.java:88) ~[spring-data-mongodb-3.2.1.jar:3.2.1]
	at de.vtlob.spring.mongodb.converter.kotlin.issue.ExampleApplication.mongoCustomConversions(ExampleApplication.kt:17) ~[classes/:na]
	at de.vtlob.spring.mongodb.converter.kotlin.issue.ExampleApplication$$EnhancerBySpringCGLIB$$f02cf75c.CGLIB$mongoCustomConversions$0(<generated>) ~[classes/:na]
	at de.vtlob.spring.mongodb.converter.kotlin.issue.ExampleApplication$$EnhancerBySpringCGLIB$$f02cf75c$$FastClassBySpringCGLIB$$e86507dc.invoke(<generated>) ~[classes/:na]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244) ~[spring-core-5.3.7.jar:5.3.7]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331) ~[spring-context-5.3.7.jar:5.3.7]
	at de.vtlob.spring.mongodb.converter.kotlin.issue.ExampleApplication$$EnhancerBySpringCGLIB$$f02cf75c.mongoCustomConversions(<generated>) ~[classes/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.3.7.jar:5.3.7]
	... 19 common frames omitted
```

**Comment by mp911de** [comment]
This is correct and a known limitation of lambdas. Lambda implementations do not provide generic type information as that is a Java limitation and we have no way of working around it.
