### ISSUE TITLE
Custom object mapping error

### ISSUE THREAD

**Issue by blueiceprj** [spring-projects/spring-data-mongodb#3795]
I used aggregation query with spring data. I converted all objectId (_id and DBRef s) data to string value. Before this operation the query in running as well. On mongodb compass also running this query. The return object is custom dto object and not a document object. But now I getting this error:

```
org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type [java.lang.String] to type [xxxxxxxxxxxxxxxxxxxxxxxxxxxxx.dto.SubjectDTO]
	at org.springframework.core.convert.support.GenericConversionService.handleConverterNotFound(GenericConversionService.java:322)
	at org.springframework.core.convert.support.GenericConversionService.convert(GenericConversionService.java:195)
```

```
public List<CourseDTO> findCoursesWithTeacherByEmployeeIdAndAcademicPeriodId(String schoolId, String employeeId,
			String academicPeriodId)
	{
		final Criteria criterias = new Criteria();
		criterias.and("deleted").is(false);
		criterias.and("schoolId").is(schoolId);
		criterias.and("academicPeriodId").is(academicPeriodId);
		criterias.orOperator(Criteria.where("primaryTeacherId").is(employeeId), Criteria.where("secondaryTeacherId").is(employeeId));

		final List<AggregationOperation> pipeline = new ArrayList<>();
		pipeline.add(Aggregation.match(criterias));

		final AddFieldOperation fields = new AddFieldOperation();
		fields.add("gradeLevelId",  "$gradeLevelId");
		fields.add("primaryTeacherId","$primaryTeacherId");
		fields.add("secondaryTeacherId","$secondaryTeacherId");
		pipeline.add(fields);

		pipeline.add(lookupOperation("school_grade_level", "gradeLevelId", "_id", "gradeLevel"));
		pipeline.add(lookupOperation("employee_info", "primaryTeacherId", "_id", "teacher"));
		pipeline.add(lookupOperation("employee_info", "secondaryTeacherId", "_id", "secondTeacher"));
		pipeline.add(unwindOperation("$gradeLevel"));
		pipeline.add(unwindOperation("$teacher"));
		pipeline.add(unwindOperation("$secondTeacher"));

		final AddFieldOperation addField = new AddFieldOperation();
		addField.add("gradeLevelName", "$gradeLevel.name");
		addField.add("firstImageUrl", "$teacher.imageUrl");
		addField.add("secondImageUrl", "$secondTeacher.imageUrl");
		addField.add("teacherFirstName", "$teacher.profile.firstName");
		addField.add("teacherLastName", "$teacher.profile.lastName");
		addField.add("teacherMiddleName", "$teacher.profile.middleName");
		addField.add("secondTeacherFirstName", "$secondTeacher.profile.firstName");
		addField.add("secondTeacherLastName", "$secondTeacher.profile.lastName");
		addField.add("secondTeacherMiddleName", "$secondTeacher.profile.middleName");
		pipeline.add(addField);
		pipeline.add(exclude("bbbServerSetting", "courseLogs", "teacher", "secondTeacher", "gradeLevel"));

		pipeline.add(Aggregation.sort(Sort.by(Sort.Direction.ASC, "name")));

		final AggregationResults<CourseDTO> aggregate = template.aggregate(pipeline.withOptions(AggregationOptions.builder().collation("en")), DocumentConstants.SCHOOL_COURSE, CourseDTO.class);
		return aggregate.getMappedResults();
	}
```

**Comment by blueiceprj** [comment]
Sorry this my bad. Wrong issue.
