### ISSUE TITLE
Backwards incompatibility in 2.5.6

### ISSUE THREAD

**Issue by sjerman** [spring-projects/spring-data-mongodb#3871]
Hi Folks,

Trying to bring our application forward to 2.5.6 and am running into an issue with @Query.

Had same issue last time I did the migration - #3401 .. maybe the fix didn't make it to 2.5

The query was:
```
  @Query(
      " ?#{ hasRole('ROLE_ADMIN') or global.getProperty('user.global') == 'true' ? {'_class': { '$eq' : 'com.kloudspot.jamesons.datamodel.domain.location.Region' }} : { '$and' : { {'_class': { '$eq' : 'com.kloudspot.jamesons.datamodel.domain.location.Region' }}, {'$or': { { 'users._id': global.getOid( principal.id ) },{'usersFromHierarchy._id': global.getOid( principal.id ) } } } } } } ")
  @Cacheable(value = "siteRegions", keyGenerator = "siteKeyGenerator")
  List<Region> findRegions();
```
Get this error:

```
org.bson.BsonInvalidOperationException: readStartDocument can only be called when CurrentBSONType is DOCUMENT, not when CurrentBSONType is UNDEFINED.
	at org.bson.AbstractBsonReader.verifyBSONType(AbstractBsonReader.java:690)
	at org.bson.AbstractBsonReader.checkPreconditions(AbstractBsonReader.java:722)
	at org.bson.AbstractBsonReader.readStartDocument(AbstractBsonReader.java:450)
	at org.springframework.data.mongodb.util.json.ParameterBindingDocumentCodec.decode(ParameterBindingDocumentCodec.java:223)
	at org.springframework.data.mongodb.util.json.ParameterBindingDocumentCodec.captureExpressionDependencies(ParameterBindingDocumentCodec.java:202)
	at org.springframework.data.mongodb.repository.query.StringBasedMongoQuery.getBindingContext(StringBasedMongoQuery.java:136)
	at org.springframework.data.mongodb.repository.query.StringBasedMongoQuery.createQuery(StringBasedMongoQuery.java:121)
	at org.springframework.data.mongodb.repository.query.AbstractMongoQuery.doExecute(AbstractMongoQuery.java:122)
	at org.springframework.data.mongodb.repository.query.AbstractMongoQuery.execute(AbstractMongoQuery.java:107)
	at org.springframework.data.repository.core.support.RepositoryMethodInvoker.doInvoke(RepositoryMethodInvoker.java:137)
	at org.springframework.data.repository.core.support.RepositoryMethodInvoker.invoke(RepositoryMethodInvoker.java:121)
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.doInvoke(QueryExecutorMethodInterceptor.java:159)
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.invoke(QueryExecutorMethodInterceptor.java:138)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:80)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215)
	at com.sun.proxy.$Proxy72.findByName(Unknown Source)
	at com.example.demo.RepoTests.testOne(RepoTests.java:40)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:688)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at 
```

**Comment by christophstrobl** [comment]
If you are referring to Spring Boot 2.5.6, using Data MongoDB 3.2.6, then the fix for #3401 is in.

**Comment by sjerman** [comment]
Yes. Those are the versions ... I have a test project that is 'stock' 2.5.6/3.2.6 giving that error. I'll do a few more checks.. just in case. Shall I upload the test project?

**Comment by sjerman** [comment]
Looking at the code it is parsing the BSON before any SPEL processing.... I guess that is the issue. 

Demo project showing issue is attached. (run RepoTests junit)

[issue.zip](https://github.com/spring-projects/spring-data-mongodb/files/7467335/issue.zip)

**Comment by christophstrobl** [comment]
thanks for the reproducer - we'll have a look.
