### ISSUE TITLE
Java 17 - Unable to make private java.time.LocalDateTime(java.time.LocalDate,java.time.LocalTime) accessible: module java.base does not "opens java.time" to unnamed module @18078bef

### ISSUE THREAD

**Issue by bjornharvold** [spring-projects/spring-data-mongodb#3893]
Hi,

I am upgrading our Java version to 17 today and encountered this error with 2 of our Spring Boot apps running MongoDb. I have looked everywhere for a solution to this problem but have been unable to find someone with a similar problem running Spring Data MongoDb. 

GSON had a similar error here: https://github.com/google/gson/issues/1507

Please advise. Do I need to change anything on my end?

The setup:
Spring Boot 2.6.0 with Spring Data MongoDb. Using all recommended versions as outlined in the parent POM.

```
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make private java.time.LocalDateTime(java.time.LocalDate,java.time.LocalTime) accessible: module java.base does not "opens java.time" to unnamed module @18078bef
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354) ~[na:na]
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297) ~[na:na]
	at java.base/java.lang.reflect.Constructor.checkCanSetAccessible(Constructor.java:188) ~[na:na]
	at java.base/java.lang.reflect.Constructor.setAccessible(Constructor.java:181) ~[na:na]
	at org.springframework.util.ReflectionUtils.makeAccessible(ReflectionUtils.java:202) ~[spring-core-5.3.13.jar:5.3.13]
	at org.springframework.data.mapping.PreferredConstructor.<init>(PreferredConstructor.java:64) ~[spring-data-commons-2.6.0.jar:2.6.0]
	at org.springframework.data.mapping.model.PreferredConstructorDiscoverer$Discoverers.buildPreferredConstructor(PreferredConstructorDiscoverer.java:222) ~[spring-data-commons-2.6.0.jar:2.6.0]
	at org.springframework.data.mapping.model.PreferredConstructorDiscoverer$Discoverers.access$200(PreferredConstructorDiscoverer.java:91) ~[spring-data-commons-2.6.0.jar:2.6.0]
	at org.springframework.data.mapping.model.PreferredConstructorDiscoverer$Discoverers$1.discover(PreferredConstructorDiscoverer.java:134) ~[spring-data-commons-2.6.0.jar:2.6.0]
	at org.springframework.data.mapping.model.PreferredConstructorDiscoverer.discover(PreferredConstructorDiscoverer.java:79) ~[spring-data-commons-2.6.0.jar:2.6.0]
	at org.springframework.data.mapping.model.BasicPersistentEntity.<init>(BasicPersistentEntity.java:112) ~[spring-data-commons-2.6.0.jar:2.6.0]
	at org.springframework.data.mongodb.core.mapping.BasicMongoPersistentEntity.<init>(BasicMongoPersistentEntity.java:84) ~[spring-data-mongodb-3.3.0.jar:3.3.0]
	at org.springframework.data.mongodb.core.mapping.MongoMappingContext.createPersistentEntity(MongoMappingContext.java:100) ~[spring-data-mongodb-3.3.0.jar:3.3.0]
	at org.springframework.data.mongodb.core.mapping.MongoMappingContext.createPersistentEntity(MongoMappingContext.java:41) ~[spring-data-mongodb-3.3.0.jar:3.3.0]
	at org.springframework.data.mapping.context.AbstractMappingContext.doAddPersistentEntity(AbstractMappingContext.java:404) ~[spring-data-commons-2.6.0.jar:2.6.0]
	at org.springframework.data.mapping.context.AbstractMappingContext.addPersistentEntity(AbstractMappingContext.java:380) ~[spring-data-commons-2.6.0.jar:2.6.0]
	at org.springframework.data.mapping.context.AbstractMappingContext$PersistentPropertyCreator.lambda$createAndRegisterProperty$3(AbstractMappingContext.java:604) ~[spring-data-commons-2.6.0.jar:2.6.0]
	at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[na:na]
	at org.springframework.data.mapping.context.AbstractMappingContext$PersistentPropertyCreator.createAndRegisterProperty(AbstractMappingContext.java:601) ~[spring-data-commons-2.6.0.jar:2.6.0]
	at org.springframework.data.mapping.context.AbstractMappingContext$PersistentPropertyCreator.doWith(AbstractMappingContext.java:555) ~[spring-data-commons-2.6.0.jar:2.6.0]
	at org.springframework.util.ReflectionUtils.doWithFields(ReflectionUtils.java:710) ~[spring-core-5.3.13.jar:5.3.13]
	at org.springframework.data.mapping.context.AbstractMappingContext.doAddPersistentEntity(AbstractMappingContext.java:423) ~[spring-data-commons-2.6.0.jar:2.6.0]
	at org.springframework.data.mapping.context.AbstractMappingContext.addPersistentEntity(AbstractMappingContext.java:380) ~[spring-data-commons-2.6.0.jar:2.6.0]
	at org.springframework.data.mapping.context.AbstractMappingContext.getPersistentEntity(AbstractMappingContext.java:265) ~[spring-data-commons-2.6.0.jar:2.6.0]
	at org.springframework.data.mapping.context.AbstractMappingContext.getPersistentEntity(AbstractMappingContext.java:208) ~[spring-data-commons-2.6.0.jar:2.6.0]
	at org.springframework.data.mapping.context.AbstractMappingContext.getPersistentEntity(AbstractMappingContext.java:91) ~[spring-data-commons-2.6.0.jar:2.6.0]
	at org.springframework.data.mapping.context.MappingContext.getRequiredPersistentEntity(MappingContext.java:73) ~[spring-data-commons-2.6.0.jar:2.6.0]
	at org.springframework.data.mongodb.repository.support.MongoRepositoryFactory.getEntityInformation(MongoRepositoryFactory.java:160) ~[spring-data-mongodb-3.3.0.jar:3.3.0]
	at org.springframework.data.mongodb.repository.support.MongoRepositoryFactory.getTargetRepository(MongoRepositoryFactory.java:134) ~[spring-data-mongodb-3.3.0.jar:3.3.0]
	at org.springframework.data.repository.core.support.RepositoryFactorySupport.getRepository(RepositoryFactorySupport.java:324) ~[spring-data-commons-2.6.0.jar:2.6.0]
	at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.lambda$afterPropertiesSet$5(RepositoryFactoryBeanSupport.java:322) ~[spring-data-commons-2.6.0.jar:2.6.0]
	at org.springframework.data.util.Lazy.getNullable(Lazy.java:230) ~[spring-data-commons-2.6.0.jar:2.6.0]
	at org.springframework.data.util.Lazy.get(Lazy.java:114) ~[spring-data-commons-2.6.0.jar:2.6.0]
	at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.afterPropertiesSet(RepositoryFactoryBeanSupport.java:328) ~[spring-data-commons-2.6.0.jar:2.6.0]
	at org.springframework.data.mongodb.repository.support.MongoRepositoryFactoryBean.afterPropertiesSet(MongoRepositoryFactoryBean.java:119) ~[spring-data-mongodb-3.3.0.jar:3.3.0]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863) ~[spring-beans-5.3.13.jar:5.3.13]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800) ~[spring-beans-5.3.13.jar:5.3.13]
	... 30 common frames omitted
```

**Comment by jxblum** [comment]
While the _Spring_ team is still in transition to moving all _Spring_ bits to Java 17, Jakarta EE 9, etc, all based on the upcoming _Spring Framework_ 6, which also requires the bits (i.e. vendors of the bits) for which we integrate with to also provide compatible support for Java 17 and so, you can in the interim, set the following JVM option when running your Spring Boot application...

```
$ java ... --add-opens java.base/java.time=ALL-UNNAMED
```

Try this; it should work as I have had to do similar things for other stores.

> DISCLAIMER: I have not specifically tried this with (_Spring Data_) MongoDB and your UC. If this does not work for the time being, please let us know in the comments.

For your reference, keep in mind that Spring Framework 6, Spring Boot 3, Spring Data 3 and so on will be the first generation based on Java 17, Jakarta EE 9 and later.

**Comment by bjornharvold** [comment]
Thanks @jxblum 

This enables me to move forward w. migration.

#greateam #greatframwork #greatsupport 

🚀🚀🚀🚀🚀🚀🚀
