### ISSUE TITLE
Issue with conversion when using aggregate function with spring-data-mongodb-3.2.2 which was working fine with spring-data-mongodb-2.1.10.RELEASE

### ISSUE THREAD

**Issue by rajeshhereforyou** [spring-projects/spring-data-mongodb#3947]
HI 

I'm trying to upgrade spring boot version of my app and hence getting spring-data-mongodb-3.2.2 

Now, I've been using mongotemplate from spring in my repository layer and I've a aggregation query which was working fine with spring-data-mongodb-2.1.10.RELEASE but causing issues with spring-data-mongodb-3.2.2 .

Here are my models.

```java
@Document(collection = "SampleCollection")
MySuperClass{

	@Id
	private UUID id;
	private String name;
	private String address;

	private String parentId; // This parentId is nothing but id of another object of type 'MySuperClass

	// getters and setters

}

@Document(collection = "SampleCollection")
MyChildClass extends MySuperClass{

	private MySuperClass field1;

}
```

Now my aggregation query is as below which was working perfectly fine with `spring-data-mongodb-2.1.10.RELEASE`.

```java
List<String> ids = //some list;
Criteria matchCriteria = new Criteria("_id").in(ids);
LookupOperation lookupOperation = LookupOperation.newLookup()
    .from("SampleCollection")
    .localField("parentId")
    .foreignField("_id")
    .as("field1");

Aggregation aggregation = Aggregation.newAggregation(match(matchCriteria), lookupOperation);
return orgTemplate.aggregate(aggregation, "SampleCollection", MyChildClass.class).getMappedResults();`
```

After upgrading to spring-data-mongodb-3.2.2, I'm getting below error. Please suggest.

```bash
org.springframework.data.mapping.MappingException: Cannot convert [Document{}] of type class java.util.ArrayList into an instance of class MySuperClass! Implement a custom Converter<class java.util.ArrayList, class MySuperClass> and register it with the CustomConversions. Parent object was: MyChildClass@a2635570 -> null
```

**Comment by christophstrobl** [comment]
Thanks for reporting! Can you please add the full stacktrace.

**Comment by rajeshhereforyou** [comment]
org.springframework.data.mapping.MappingException: Cannot convert [Document{}] of type class java.util.ArrayList into an instance of class MySuperClass! Implement a custom Converter<class java.util.ArrayList, class MySuperClass> and register it with the CustomConversions. Parent object was: MyChildClass@a2635570 -> null
		at org.springframework.data.mongodb.core.convert.MappingMongoConverter$ConversionContext.convert(MappingMongoConverter.java:1895)
			at org.springframework.data.mongodb.core.convert.MappingMongoConverter$MongoDbPropertyValueProvider.getPropertyValue(MappingMongoConverter.java:1636)
			at org.springframework.data.mongodb.core.convert.MappingMongoConverter.readProperties(MappingMongoConverter.java:477)
			at org.springframework.data.mongodb.core.convert.MappingMongoConverter.populateProperties(MappingMongoConverter.java:392)
			at org.springframework.data.mongodb.core.convert.MappingMongoConverter.read(MappingMongoConverter.java:371)
			at org.springframework.data.mongodb.core.convert.MappingMongoConverter.readDocument(MappingMongoConverter.java:341)
			at org.springframework.data.mongodb.core.convert.MappingMongoConverter.read(MappingMongoConverter.java:277)
			at org.springframework.data.mongodb.core.convert.MappingMongoConverter.read(MappingMongoConverter.java:273)
			at org.springframework.data.mongodb.core.convert.MappingMongoConverter.read(MappingMongoConverter.java:102)
			at org.springframework.data.mongodb.core.MongoTemplate$ReadDocumentCallback.doWith(MongoTemplate.java:3178)
			at org.springframework.data.mongodb.core.MongoTemplate.lambda$null$24(MongoTemplate.java:2188)
			at com.mongodb.client.internal.MappingIterable$1.apply(MappingIterable.java:57)
			at com.mongodb.client.internal.MongoIterableImpl.forEach(MongoIterableImpl.java:113)
			at com.mongodb.client.internal.MappingIterable.forEach(MappingIterable.java:54)
			at com.mongodb.client.internal.MappingIterable.into(MappingIterable.java:64)
			at org.springframework.data.mongodb.core.MongoTemplate.lambda$doAggregate$25(MongoTemplate.java:2191)
			at org.springframework.data.mongodb.core.MongoTemplate.execute(MongoTemplate.java:553)
			at org.springframework.data.mongodb.core.MongoTemplate.doAggregate(MongoTemplate.java:2148)
			at org.springframework.data.mongodb.core.MongoTemplate.doAggregate(MongoTemplate.java:2117)
			at org.springframework.data.mongodb.core.MongoTemplate.aggregate(MongoTemplate.java:2111)
			at org.springframework.data.mongodb.core.MongoTemplate.aggregate(MongoTemplate.java:2012)

**Comment by christophstrobl** [comment]
After looking at the issue, the behavior you experienced in previous versions was more of a bug than a feature. The `$lookup` stage will provide you with a collection of matching documents, which in turn need to be mapped to a collection like type (`List`, `Set`, ...) and cannot be turned into a single value. 

There are basically two options here.
1) turn the field into a collection.
2) update the aggregation.

If you want to opt for the 2nd option here's what it could look like.

```java
// ...

ProjectionOperation projectOp = project(MyChildClass.class)
	.and(arrayOf("field1").first()).as("field1");

Aggregation aggregation = Aggregation.newAggregation(match(matchCriteria), lookupOperation, projectOp);
```

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
