### ISSUE TITLE
Can't find a codec for class java.time.Instant

### ISSUE THREAD

**Issue by azmhyy2021** [spring-projects/spring-data-mongodb#3968]
Hello,

I'm working on developing authentication system with 
spring session mongodb and spring data mongodb reactive.

After I login a session successfully, every time an exception is occured.
The error message is as follow.

It says java.time.Instant is not found.

Is this a bug ?

```
SLF4J: Failed toString() invocation on an object of type [com.mongodb.BasicDBObject]
Reported exception:
org.bson.codecs.configuration.CodecConfigurationException: Can't find a codec for class java.time.Instant.
	at org.bson.internal.CodecCache.lambda$getOrThrow$1(CodecCache.java:52)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at org.bson.internal.CodecCache.getOrThrow(CodecCache.java:51)
	at org.bson.internal.OverridableUuidRepresentationCodecRegistry.get(OverridableUuidRepresentationCodecRegistry.java:72)
	at org.bson.internal.ChildCodecRegistry.get(ChildCodecRegistry.java:52)
	at com.mongodb.DBObjectCodec.writeValue(DBObjectCodec.java:245)
	at com.mongodb.DBObjectCodec.encode(DBObjectCodec.java:159)
	at com.mongodb.DBObjectCodec.encode(DBObjectCodec.java:67)
	at com.mongodb.BasicDBObject.toJson(BasicDBObject.java:204)
	at com.mongodb.BasicDBObject.toJson(BasicDBObject.java:177)
	at com.mongodb.BasicDBObject.toJson(BasicDBObject.java:164)
	at com.mongodb.BasicDBObject.toString(BasicDBObject.java:251)
	at org.slf4j.helpers.MessageFormatter.safeObjectAppend(MessageFormatter.java:277)
	at org.slf4j.helpers.MessageFormatter.deeplyAppendParameter(MessageFormatter.java:249)
	at org.slf4j.helpers.MessageFormatter.arrayFormat(MessageFormatter.java:211)
	at org.slf4j.helpers.MessageFormatter.arrayFormat(MessageFormatter.java:161)
	at ch.qos.logback.classic.spi.LoggingEvent.getFormattedMessage(LoggingEvent.java:293)
	at ch.qos.logback.classic.spi.LoggingEvent.prepareForDeferredProcessing(LoggingEvent.java:206)
	at ch.qos.logback.core.OutputStreamAppender.subAppend(OutputStreamAppender.java:223)
	at ch.qos.logback.core.OutputStreamAppender.append(OutputStreamAppender.java:102)
	at ch.qos.logback.core.UnsynchronizedAppenderBase.doAppend(UnsynchronizedAppenderBase.java:84)
	at ch.qos.logback.core.spi.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:51)
	at ch.qos.logback.classic.Logger.appendLoopOnAppenders(Logger.java:270)
	at ch.qos.logback.classic.Logger.callAppenders(Logger.java:257)
	at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:421)
	at ch.qos.logback.classic.Logger.filterAndLog_1(Logger.java:398)
	at ch.qos.logback.classic.Logger.debug(Logger.java:486)
	at org.springframework.data.mongodb.core.mapping.event.AbstractMongoEventListener.onBeforeConvert(AbstractMongoEventListener.java:106)
	at org.springframework.data.mongodb.core.mapping.event.AbstractMongoEventListener.onApplicationEvent(AbstractMongoEventListener.java:87)
	at org.springframework.data.mongodb.core.mapping.event.AbstractMongoEventListener.onApplicationEvent(AbstractMongoEventListener.java:31)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:421)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:378)
	at org.springframework.data.mongodb.core.ReactiveMongoTemplate.maybeEmitEvent(ReactiveMongoTemplate.java:2631)
	at org.springframework.data.mongodb.core.ReactiveMongoTemplate.lambda$doSave$52(ReactiveMongoTemplate.java:1535)
	at 
.....
```

**Comment by azmhyy2021** [comment]
`
@Configuration
public class constraintConfig {
  @Bean
  public ValidatingMongoEventListener validatingMongoEventListener() {
    return new ValidatingMongoEventListener(validator());
  }

  @Bean
  public LocalValidatorFactoryBean validator() {
    return new LocalValidatorFactoryBean();
  }
}
`

I found the above code caused the error.

**Comment by christophstrobl** [comment]
@azmhyy2021 thanks for reporting!
