### ISSUE TITLE
`Local…` JSR-310 types conversion

### ISSUE THREAD

**Issue by authub** [spring-projects/spring-data-mongodb#4019]
This is my code :
```java

@SpringBootTest
public class Test1 {
    @Resource
    MongoTemplate mongoTemplate;

  @Test
    public void test() {
        LocalDateTimeTest test = new LocalDateTimeTest();
        LocalDateTime of = LocalDateTime.of(2022, 1, 2, 18, 0, 0);
        test.setLocalDateTime(of);
        test.setLocalDate(of.toLocalDate());
        test.setLocalTime(of.toLocalTime());
        System.err.println(JacksonUtil.toJsonStr(test));
        this.mongoTemplate.insert(test);
        List<LocalDateTimeTest> all = this.mongoTemplate.findAll(LocalDateTimeTest.class);
        System.err.println(JacksonUtil.toJsonStr(all));
    }

    @Data
    @ToString(callSuper = true)
    @Document(collection = "localDateTimeTest")
    public static class LocalDateTimeTest implements Serializable {
        private static final long serialVersionUID = -96651919949624932L;

        @Id
        private String id;
        private LocalDate localDate;
        private LocalTime localTime;
        private LocalDateTime localDateTime;

    }

}
```

Primary execution log:
```json

{"localDate":"2022-01-02","localTime":"18:00:00","localDateTime":"2022-01-02 18:00:00"}
```
14:42:39.654 [main] DEBUG o.s.d.m.c.MongoTemplate - [insertDocument,1476] - Inserting Document containing fields: [localDate, localTime, localDateTime, _class] in collection: localDateTimeTest
14:42:39.781 [main] INFO  o.m.d.connection - [info,71] - Opened connection [connectionId{localValue:3, serverValue:37}] to localhost:27017
```json
[{"id":"624fd95f15bf92643366ae50","localDate":"2022-01-02","localTime":"18:00:00","localDateTime":"2022-01-02 18:00:00"}]
```

Data stored in the mongodb service:
```json
{
  "_id": {
    "$oid": "624fd70bcde51e79c0e36506"
  },
  "localDate": {
    "$date": "2022-01-01T16:00:00Z"
  },
  "localTime": {
    "$date": "2022-04-08T10:00:00Z"
  },
  "localDateTime": {
    "$date": "2022-01-02T10:00:00Z"
  },
  "_class": "com.exam.Test1$LocalDateTimeTest"
}
```

As you can see, the data I finally store is not the data I want to store, because we are not in the same hemisphere. I searched the and documents, but I didn't find a problem that can configure this time zone.

**Comment by Sylvain-maillard** [comment]
Hello, I think this is because MongoDB store Date with UTC timezone: https://www.mongodb.com/docs/manual/reference/bson-types/#std-label-document-bson-type-date

You can keep the offset/timezone by adding some custom read and write converters, converting the Date to a specific Document containing the date in UTC plus the timezone. 

Exemple in kotlin:

`````kotlin 
 @WritingConverter
    private object OffsetDateTimeWriteConverter : Converter<OffsetDateTime, Document> {
        override fun convert(zonedDateTime: OffsetDateTime): Document = Document().apply {
            put("date", Date.from(zonedDateTime.toInstant()))
            put("nano", zonedDateTime.nano)
            put("offset", zonedDateTime.offset.id)
        }
    }

    @ReadingConverter
    private object OffsetDateTimeReadConverter : Converter<Document, OffsetDateTime> {
        override fun convert(date: Document): OffsetDateTime = (date["date"] as Date)
            .toInstant()
            .atOffset(ZoneOffset.of(date["offset"] as String))
            .withNano(date["nano"] as Int)
    }

`````
(note that Mongo do not store the nano part of the date too)
You can also use a fixed offset/timezone while deserializing if you want to stick with LocalDateTime

**Comment by authub** [comment]
```java

@Component
public class MyConverter {
    @Component
    @WritingConverter
    public static class WritingOffsetDateTime implements Converter<OffsetDateTime, Document> {
        @Override
        public Document convert(OffsetDateTime zonedDateTime) {
            Document document = new Document();
            document.put("date", Date.from(zonedDateTime.toInstant()));
            document.put("nano", zonedDateTime.getNano());
            document.put("offset", zonedDateTime.getOffset().getId());
            return document;
        }
    }

    @Component
    @ReadingConverter
    public static class ReadingOffsetDateTime implements Converter<Document, OffsetDateTime> {

        @Override
        public OffsetDateTime convert(Document source) {
            Date date = source.getDate("data");
            OffsetDateTime offsetDateTime = date.toInstant()
                    .atOffset(ZoneOffset.of(source.getString("offset")))
                    .withNano(source.getInteger("nano"));
            return offsetDateTime;
        }
    }
}
```


```java

import com.fasterxml.jackson.databind.ObjectMapper;
import lombok.Data;
import lombok.SneakyThrows;
import lombok.ToString;
import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.MongoTemplate;
import org.springframework.data.mongodb.core.mapping.Document;

import javax.annotation.Resource;
import java.io.Serializable;
import java.time.OffsetDateTime;
import java.time.OffsetTime;
import java.time.ZoneOffset;
import java.util.List;

/**
 * @title OffsetDateTimeTest.java
 */
@Slf4j
@SpringBootTest
public class OffsetDateTimeTest {
    @Resource
    MongoTemplate mongoTemplate;
    @Resource
    ObjectMapper mapper;

    @SneakyThrows
    @org.junit.jupiter.api.Test
    public void test() {
        OffsetDateTimeDocument document = new OffsetDateTimeDocument();
        OffsetDateTime dateTime = OffsetDateTime.of(2022, 1, 2, 18, 0, 0, 0, ZoneOffset.UTC);
        document.setOffsetDateTime(dateTime);
        document.setOffsetTime(dateTime.toOffsetTime());
        System.err.println(this.mapper.writeValueAsString(document));
        this.mongoTemplate.insert(document);
        List<LocalDateTimeTest> all = this.mongoTemplate.findAll(LocalDateTimeTest.class);
        System.err.println(this.mapper.writeValueAsString(all));
    }

    @Data
    @ToString(callSuper = true)
    @Document(collection = "offsetDateTimeDocument")
    public static class OffsetDateTimeDocument implements Serializable {
        private static final long serialVersionUID = -96651919949624932L;

        @Id
        private String id;
        private OffsetTime offsetTime;
        private OffsetDateTime offsetDateTime;

    }
}

```

```json
{"offsetTime":"18:00Z","offsetDateTime":"2022-01-03T02:00:00+08:00"}
```
19:57:18.444 [main] DEBUG o.s.d.m.c.MongoTemplate - [insertDocument,1476] - Inserting Document containing fields: [offsetTime, offsetDateTime, _class] in collection: offsetDateTimeDocument
19:57:18.654 [main] INFO  o.m.d.connection - [info,71] - Opened connection [connectionId{localValue:3, serverValue:104}] to localhost:27017

org.bson.codecs.configuration.CodecConfigurationException: Can't find a codec for class java.time.OffsetTime.

	at org.bson.internal.CodecCache.lambda$getOrThrow$1(CodecCache.java:52)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at org.bson.internal.CodecCache.getOrThrow(CodecCache.java:51)
	at org.bson.internal.OverridableUuidRepresentationCodecRegistry.get(OverridableUuidRepresentationCodecRegistry.java:72)
	at org.bson.internal.ChildCodecRegistry.get(ChildCodecRegistry.java:52)
	at org.bson.codecs.DocumentCodec.writeValue(DocumentCodec.java:206)
	at org.bson.codecs.DocumentCodec.encode(DocumentCodec.java:165)
	at org.bson.codecs.DocumentCodec.encode(DocumentCodec.java:44)
	at org.bson.codecs.BsonDocumentWrapperCodec.encode(BsonDocumentWrapperCodec.java:63)
	at org.bson.codecs.BsonDocumentWrapperCodec.encode(BsonDocumentWrapperCodec.java:29)
	at com.mongodb.internal.connection.SplittablePayload$WriteRequestEncoder.encode(SplittablePayload.java:200)
	at com.mongodb.internal.connection.SplittablePayload$WriteRequestEncoder.encode(SplittablePayload.java:187)
	at org.bson.codecs.BsonDocumentWrapperCodec.encode(BsonDocumentWrapperCodec.java:63)
	at org.bson.codecs.BsonDocumentWrapperCodec.encode(BsonDocumentWrapperCodec.java:29)
	at com.mongodb.internal.connection.BsonWriterHelper.writeDocument(BsonWriterHelper.java:77)
	at com.mongodb.internal.connection.BsonWriterHelper.writePayload(BsonWriterHelper.java:59)
	at com.mongodb.internal.connection.CommandMessage.encodeMessageBodyWithMetadata(CommandMessage.java:168)
	at com.mongodb.internal.connection.RequestMessage.encode(RequestMessage.java:138)
	at com.mongodb.internal.connection.CommandMessage.encode(CommandMessage.java:62)
	at com.mongodb.internal.connection.InternalStreamConnection.sendAndReceive(InternalStreamConnection.java:326)
	at com.mongodb.internal.connection.UsageTrackingInternalConnection.sendAndReceive(UsageTrackingInternalConnection.java:116)
	at com.mongodb.internal.connection.DefaultConnectionPool$PooledConnection.sendAndReceive(DefaultConnectionPool.java:647)
	at com.mongodb.internal.connection.CommandProtocolImpl.execute(CommandProtocolImpl.java:71)
	at com.mongodb.internal.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:244)
	at com.mongodb.internal.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:227)
	at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:127)
	at com.mongodb.internal.connection.DefaultServer$OperationCountTrackingConnection.command(DefaultServer.java:357)
	at com.mongodb.internal.operation.MixedBulkWriteOperation.executeCommand(MixedBulkWriteOperation.java:477)
	at com.mongodb.internal.operation.MixedBulkWriteOperation.executeBulkWriteBatch(MixedBulkWriteOperation.java:339)
	at com.mongodb.internal.operation.MixedBulkWriteOperation.lambda$execute$2(MixedBulkWriteOperation.java:260)
	at com.mongodb.internal.operation.OperationHelper.lambda$withSourceAndConnection$2(OperationHelper.java:564)
	at com.mongodb.internal.operation.OperationHelper.withSuppliedResource(OperationHelper.java:589)
	at com.mongodb.internal.operation.OperationHelper.lambda$withSourceAndConnection$3(OperationHelper.java:563)
	at com.mongodb.internal.operation.OperationHelper.withSuppliedResource(OperationHelper.java:589)
	at com.mongodb.internal.operation.OperationHelper.withSourceAndConnection(OperationHelper.java:562)
	at com.mongodb.internal.operation.MixedBulkWriteOperation.lambda$execute$3(MixedBulkWriteOperation.java:232)
	at com.mongodb.internal.async.function.RetryingSyncSupplier.get(RetryingSyncSupplier.java:65)
	at com.mongodb.internal.operation.MixedBulkWriteOperation.execute(MixedBulkWriteOperation.java:268)
	at com.mongodb.internal.operation.MixedBulkWriteOperation.execute(MixedBulkWriteOperation.java:84)
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:212)
	at com.mongodb.client.internal.MongoCollectionImpl.executeSingleWriteRequest(MongoCollectionImpl.java:1010)
	at com.mongodb.client.internal.MongoCollectionImpl.executeInsertOne(MongoCollectionImpl.java:471)
	at com.mongodb.client.internal.MongoCollectionImpl.insertOne(MongoCollectionImpl.java:454)
	at com.mongodb.client.internal.MongoCollectionImpl.insertOne(MongoCollectionImpl.java:448)
	at org.springframework.data.mongodb.core.MongoTemplate.lambda$insertDocument$16(MongoTemplate.java:1485)
	at org.springframework.data.mongodb.core.MongoTemplate.execute(MongoTemplate.java:560)
	at org.springframework.data.mongodb.core.MongoTemplate.insertDocument(MongoTemplate.java:1479)
	at org.springframework.data.mongodb.core.MongoTemplate.doInsert(MongoTemplate.java:1279)
	at org.springframework.data.mongodb.core.MongoTemplate.insert(MongoTemplate.java:1194)
	at org.springframework.data.mongodb.core.MongoTemplate.insert(MongoTemplate.java:1179)
	at com.exam.OffsetDateTimeTest.test(OffsetDateTimeTest.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:214)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:210)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:135)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:66)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:71)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)

The converter is not effective？

**Comment by Sylvain-maillard** [comment]
You should add the custom converters to the MongoTemplate. See this link: https://stackoverflow.com/a/47222078/1891891

**Comment by mp911de** [comment]
As mentioned, MongoDB's temporal types are stored as [milliseconds since 1.1.1970 UTC](https://www.mongodb.com/docs/manual/reference/bson-types/#date) while `LocalDateTime` and other `Local…` types describe a local temporal value that isn't related to the UTC timezone, but a timezone-less representation. 

Depending on your use-case, you can store `Instant` values to natively map the point in time and convert `Instant` into your `Local…` representation. Alternatively, if you want to store zoned temporal values (`ZonedDateTime`, `OffsetDateTime`), you need to register converters as mentioned in https://github.com/spring-projects/spring-data-mongodb/issues/4019#issuecomment-1110824256. Converters must be registered with a `CustomConversions` object, those aren't automatically discovered by the Spring container. Simply create a `MongoCustomConversions` bean (when using Spring Boot) using the code along the lines of:

```java
MongoCustomConversions.create(config -> {config.registerConverter(…)})
```
