### ISSUE TITLE
Spring Tests - MongoSocketException

### ISSUE THREAD

**Issue by vinsguru** [spring-projects/spring-data-mongodb#4068]
I see this exception every single time when I use Mongo as part of my Spring tests.

This is very easy to replicate. (I tried with Spring boot versions `2.6.6`, `2.6.7` and `2.7.0`.)

**pom.xml**
```
	<properties>
		<java.version>17</java.version>
		<testcontainers.version>1.17.2</testcontainers.version>
	</properties>
        <dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-mongodb-reactive</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>io.projectreactor</groupId>
			<artifactId>reactor-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.testcontainers</groupId>
			<artifactId>junit-jupiter</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.testcontainers</groupId>
				<artifactId>testcontainers-bom</artifactId>
				<version>${testcontainers.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>
```		

**Test**

```
@SpringBootTest
@Testcontainers
class MongoTests {

	@Autowired
	private ReactiveMongoTemplate template;

	@Container
	public static final GenericContainer<?> mongo = new GenericContainer<>(DockerImageName.parse("mongo"))
			.withExposedPorts(27017)
			.waitingFor(Wait.forListeningPort());


	@DynamicPropertySource
	static void mongoProperties(DynamicPropertyRegistry registry) throws InterruptedException {
		mongo.start();
		registry.add("spring.data.mongodb.uri", () -> String.format("mongodb://%s:%s/admin", mongo.getHost(), mongo.getMappedPort(27017)));
	}

	@Test
	void test() {
		System.out.println("Just check the logs");
		System.out.println(template);
	}

}
```

**log**: 
```
2022-05-29 15:10:41.603  INFO 39393 --- [localhost:52857] org.mongodb.driver.connection            : Opened connection [connectionId{localValue:1, serverValue:2}] to localhost:52857
2022-05-29 15:10:41.604  INFO 39393 --- [localhost:52857] org.mongodb.driver.connection            : Opened connection [connectionId{localValue:2, serverValue:1}] to localhost:52857
2022-05-29 15:10:41.605  INFO 39393 --- [localhost:52857] org.mongodb.driver.cluster               : Monitor thread successfully connected to server with description ServerDescription{address=localhost:52857, type=STANDALONE, state=CONNECTED, ok=true, minWireVersion=0, maxWireVersion=13, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=30, roundTripTimeNanos=36978375}
2022-05-29 15:10:41.969  INFO 39393 --- [           main] .v.s.MongoTests : Started MongoTests in 1.715 seconds (JVM running for 6.057)
2022-05-29 15:10:42.514  INFO 39393 --- [localhost:52857] org.mongodb.driver.cluster               : Exception in monitor thread while connecting to server localhost:52857

com.mongodb.MongoSocketReadException: Prematurely reached end of stream
	at com.mongodb.internal.connection.AsynchronousChannelStream$BasicCompletionHandler.completed(AsynchronousChannelStream.java:247) ~[mongodb-driver-core-4.4.2.jar:na]
	at com.mongodb.internal.connection.AsynchronousChannelStream$BasicCompletionHandler.completed(AsynchronousChannelStream.java:233) ~[mongodb-driver-core-4.4.2.jar:na]
	at java.base/sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:129) ~[na:na]
	at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.finishRead(UnixAsynchronousSocketChannelImpl.java:447) ~[na:na]
	at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.finish(UnixAsynchronousSocketChannelImpl.java:195) ~[na:na]
	at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.onEvent(UnixAsynchronousSocketChannelImpl.java:217) ~[na:na]
	at java.base/sun.nio.ch.KQueuePort$EventHandlerTask.run(KQueuePort.java:312) ~[na:na]
	at java.base/sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:113) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

```

It says exception in monitor thread. But my tests work just fine. However I am trying to understand what is causing this error. 
(may be Mongo driver issue?)

**Comment by christophstrobl** [comment]
This looks like something better addressed by the team at MongoDB. Maybe the [community forum](https://www.mongodb.com/community/forums/) can help, or open an issue for the [Java Driver](https://jira.mongodb.org/projects/JAVA).
