### ISSUE TITLE
_class not inserted when using with Custom Converter

### ISSUE THREAD

**Issue by bwgjoseph** [spring-projects/spring-data-mongodb#4230]
Hi,

I'm not quite sure if this is a bug, or I missed out certain configuration. 

I have a reproduce ready at [Github]

In summary, I have a document 

```java
@TypeAlias("cinfo")
@Document("cinfo")
public class CInfo implements ReferenceAble {}
```

Where I register the converter

```java
@Configuration
public class MongoConfig {
    @Bean
    MongoCustomConversions conversions() {
        return new MongoCustomConversions(List.of(new ReferenceAbleConverter()));
    }
}
```

The converter is just a simple `@WritingConverter`

```java
@WritingConverter
public class ReferenceAbleConverter implements Converter<ReferenceAble, DocumentPointer<Document>> {

    @Override
    public DocumentPointer<Document> convert(ReferenceAble source) {
        return source::toReference;
    }

}
```

When I run the test

```java
@DataMongoTest(excludeAutoConfiguration = EmbeddedMongoAutoConfiguration.class)
@Import(MongoConfig.class)
public class DocRefTests {
    @Autowired
    private CInfoRepository cInfoRepository;

    @Test
    void test1() {
        CInfo cInfo = CInfo.builder().cinfo("cinfo").build();
        CInfo createdCInfo = this.cInfoRepository.insert(cInfo);

        log.info("{}", createdCInfo);
    }
}
```

The log shows the following

```log
2022-11-14 22:53:21.837 DEBUG 9512 --- [           main] o.s.data.mongodb.core.MongoTemplate      : Inserting Document containing fields: [cinfo] in collection: cinfo

{
    _id: ObjectId('6372531b8e27062bdd80046f'),
    cinfo: 'cinfo'
}
```

But if I don't import `MongoConfig.class`, then the output would be

```log
2022-11-14 22:54:05.211 DEBUG 28056 --- [           main] o.s.data.mongodb.core.MongoTemplate      : Inserting Document containing fields: [cinfo, _class] in collection: cinfo

{
    _id: ObjectId('63725335c2a1c4466a4fdf38'),
    cinfo: 'cinfo',
    _class: 'cinfo'
}
```

Notice that `_class` is not being inserted to the document in the first test

Thanks!

**Comment by mp911de** [comment]
Converters are intended to convert between domain types and store-native types. In your case, it is a `Document` that you need to convert to. `DocumentPointer` is not a store-native type, it's an intermediate Spring Data type.

Type hints are not written by intent as a custom converter is expected to encapsulate the entire implementation that is required to convert back and forth. Also, if you provide a writing converter, then you must provide a reading converter as well, otherwise Spring Data has no way to know how to read your data back.

**Comment by bwgjoseph** [comment]
I'm actually basing off the [@DocumentReference](https://docs.spring.io/spring-data/mongodb/docs/current/reference/html/#mapping-usage.document-references) documentation `Example 201`.

If `_class` (`@TypeAlias`) is not stored, there will be issues when it tries to read the document and cast it back. I am not exactly sure of the inner workings, but I would assume that in this case, `@ReadingConverter` is not required since (I think) that having the `@DocumentReference` does the job of reading it and casting back to the object for me, is that not the case?

So I thought that it was a bug of sort, hence, I only reported with the minimal setup I could to reproduce it, and was not aware of the `DocumentPointer`. However, this is still an issue for me, and I'm not sure how this should be overcome if I cannot use `DocumentPointer`.

---

The additional setup I have was to have a separate class which has a `@DocumentReference` back to `CInfo` as such

```java
@TypeAlias("storage")
@Document("storage")
public class Storage {
    @Id
    private String id;
    private String name;
    @DocumentReference(lookup = "{ '_id': new ObjectId('?#{id}')", collection = "?#{ref}", lazy = true)
    private CInfo cInfo;
}
```

I changed `CInfo` to an abstract class, and created a `SubCInfo`

```java
@Document("cinfo")
public abstract class CInfo implements ReferenceAble {
    @Id
    private String id;
    private String cinfo;

    @Override
    public org.bson.Document toReference() {
        return new org.bson.Document("id", this.getId()).append("ref", "cinfo");
    }
}

@TypeAlias("cinfo")
public class SubCInfo extends CInfo {
    private String subCInfo;
}
```

I have no problem saving the document, but I have an issue when retrieving it via `findById`

```java
void test1() {
	CInfo cInfo = SubCInfo.builder().cinfo("cinfo").subCInfo("subcinfo").build();
	CInfo createdCInfo = this.cInfoRepository.insert(cInfo);

	log.info("{}", createdCInfo);

	Storage storage = Storage.builder().name("StorageName").cInfo(createdCInfo).build();
	Storage createdStorage = this.storageRepository.insert(storage);

	log.info("{}", createdStorage);
	log.info("{}", createdStorage.getCInfo());

        // no issue saving above
       // throws exception when using find
	Storage findStorage = this.storageRepository.findById(createdStorage.getId()).get();

	log.info("{}", findStorage);
	log.info("{}", findStorage.getCInfo());
}
```

When I tried to get `Storage` via `findById`, and attempt to get `getCInfo`, it will throw an exception stating `abstract class cannot be initialized` or something along the line. I believe that this error is only thrown if I did not have the `_class (@TypeAlias)` stored. I did tried to manually insert the `TypeAlias` in the database, and it does works (able to cast correctly).

I understand this may sound like an issue for `StackOverflow` but since `@DocumentReference` the use case, and the documentation states to use `DocumentPointer`, but it does not store the `TypeAlias` which resulted in `@DocumentReference` not being able to cast to the correct subclass. So I would like to know what is the alternative as I am not able to use `Document` at the converter over `DocumentPointer`.

I have updated my repo to include the changes I have mentioned above.

---

Side note: I am not sure what happens but my previous setup was working fine, but while writing this, and updating my github repo, and when running the test, I am facing this exception

<details>
<summary>Click to show stacktrace</summary>

```
SLF4J: Failed toString() invocation on an object of type [com.bwgjoseph.sdmdocrefbug.CInfo$$EnhancerByCGLIB$$3c20117c]
Reported exception:
org.springframework.data.mongodb.LazyLoadingException: Unable to lazily resolve DBRef!; nested exception is org.bson.json.JsonParseException: JSON reader was expecting a name but found '<eof>'.
	at org.springframework.data.mongodb.core.convert.LazyLoadingProxyFactory$LazyLoadingInterceptor.resolve(LazyLoadingProxyFactory.java:297)
	at org.springframework.data.mongodb.core.convert.LazyLoadingProxyFactory$LazyLoadingInterceptor.ensureResolved(LazyLoadingProxyFactory.java:198)
	at org.springframework.data.mongodb.core.convert.LazyLoadingProxyFactory$LazyLoadingInterceptor.intercept(LazyLoadingProxyFactory.java:183)
	at com.bwgjoseph.sdmdocrefbug.CInfo$$EnhancerByCGLIB$$3c20117c.toString(<generated>)
	at org.slf4j.helpers.MessageFormatter.safeObjectAppend(MessageFormatter.java:277)
	at org.slf4j.helpers.MessageFormatter.deeplyAppendParameter(MessageFormatter.java:249)
	at org.slf4j.helpers.MessageFormatter.arrayFormat(MessageFormatter.java:211)
	at org.slf4j.helpers.MessageFormatter.arrayFormat(MessageFormatter.java:161)
	at ch.qos.logback.classic.spi.LoggingEvent.getFormattedMessage(LoggingEvent.java:293)
	at ch.qos.logback.classic.spi.LoggingEvent.prepareForDeferredProcessing(LoggingEvent.java:206)
	at ch.qos.logback.core.OutputStreamAppender.subAppend(OutputStreamAppender.java:223)
	at ch.qos.logback.core.OutputStreamAppender.append(OutputStreamAppender.java:102)
	at ch.qos.logback.core.UnsynchronizedAppenderBase.doAppend(UnsynchronizedAppenderBase.java:84)
	at ch.qos.logback.core.spi.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:51)
	at ch.qos.logback.classic.Logger.appendLoopOnAppenders(Logger.java:270)
	at ch.qos.logback.classic.Logger.callAppenders(Logger.java:257)
	at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:421)
	at ch.qos.logback.classic.Logger.filterAndLog_1(Logger.java:398)
	at ch.qos.logback.classic.Logger.info(Logger.java:583)
	at com.bwgjoseph.sdmdocrefbug.DocRefTests.test1(DocRefTests.java:36)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:214)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:210)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:135)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:66)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:95)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:91)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:60)
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestReference.run(JUnit5TestReference.java:98)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: org.bson.json.JsonParseException: JSON reader was expecting a name but found '<eof>'.
	at org.springframework.data.mongodb.util.json.ParameterBindingJsonReader.readBsonType(ParameterBindingJsonReader.java:184)
	at org.springframework.data.mongodb.util.json.ParameterBindingDocumentCodec.decode(ParameterBindingDocumentCodec.java:237)
	at org.springframework.data.mongodb.util.json.ParameterBindingDocumentCodec.decode(ParameterBindingDocumentCodec.java:181)
	at org.springframework.data.mongodb.core.convert.ReferenceLookupDelegate.computeFilter(ReferenceLookupDelegate.java:306)
	at org.springframework.data.mongodb.core.convert.ReferenceLookupDelegate.readReference(ReferenceLookupDelegate.java:107)
	at org.springframework.data.mongodb.core.convert.DefaultReferenceResolver.lambda$createLazyLoadingProxy$2(DefaultReferenceResolver.java:112)
	at org.springframework.data.mongodb.core.convert.LazyLoadingProxyFactory$LazyLoadingInterceptor.resolve(LazyLoadingProxyFactory.java:287)
	... 88 more
	Suppressed: org.bson.json.JsonParseException: Trying to read past EOF.
		at org.springframework.data.mongodb.util.json.JsonBuffer.read(JsonBuffer.java:50)
		at org.springframework.data.mongodb.util.json.JsonScanner.nextToken(JsonScanner.java:70)
		at org.springframework.data.mongodb.util.json.ParameterBindingJsonReader.popToken(ParameterBindingJsonReader.java:755)
		at org.springframework.data.mongodb.util.json.ParameterBindingJsonReader.readBsonType(ParameterBindingJsonReader.java:169)
		at org.bson.AbstractBsonReader.verifyBSONType(AbstractBsonReader.java:679)
		at org.bson.AbstractBsonReader.checkPreconditions(AbstractBsonReader.java:721)
		at org.bson.AbstractBsonReader.readObjectId(AbstractBsonReader.java:421)
		at org.bson.codecs.ObjectIdCodec.decode(ObjectIdCodec.java:36)
		at org.bson.codecs.ObjectIdCodec.decode(ObjectIdCodec.java:28)
		at org.springframework.data.mongodb.util.json.ParameterBindingDocumentCodec.readValue(ParameterBindingDocumentCodec.java:371)
		at org.springframework.data.mongodb.util.json.ParameterBindingDocumentCodec.decode(ParameterBindingDocumentCodec.java:248)
		... 93 more
2022-11-15 21:48:18.018  INFO 23060 --- [           main] com.bwgjoseph.sdmdocrefbug.DocRefTests   : [FAILED toString()]
```

</details>

Let me know if this is should be reported separately / elsewhere.

Thanks!

**Comment by mp911de** [comment]
Thank you for the additional details. The stack trace is helping indeed as we had previously a different understanding of the issue.

**Comment by bwgjoseph** [comment]
Hi,

Like to check if there is any update to this issue? Thank you.

**Comment by bwgjoseph** [comment]
Hi,

Check-in to see if there is any update to this issue. Thanks

**Comment by bwgjoseph** [comment]
Managed to figured (thanks to my colleague for catching it) out the cause of the exception (in the stack trace above), was due to the in-correct syntax when writing `@DocumentReference`

```java
// this is wrong
@DocumentReference(lookup = "{ '_id': new ObjectId('?#{id}')", collection = "?#{ref}", lazy = true)
// this is correct
@DocumentReference(lookup = "{ '_id' : new ObjectId('?#{id})' }", collection = "?#{ref}", lazy = true)
``` 

There was a missing closing `}` at the end of `lookup`

In addition to this, we also found out that my use-case works when we don't annotate with `@WritingConverter`

```java
// @WritingConverter << remove this
public class ReferenceAbleConverter implements Converter<ReferenceAble, DocumentPointer<Document>> {

    @Override
    public DocumentPointer<Document> convert(ReferenceAble source) {
        return source::toReference;
    }

}
```

I dig a bit more into the docs [here](https://docs.spring.io/spring-data/mongodb/docs/current/reference/html/#mongo.custom-converters.xml) and [here](https://docs.spring.io/spring-data/mongodb/docs/current/reference/html/#customconversions.converter-disambiguation)

> If you write a Converter whose source and target type are native types, we cannot determine whether we should consider it as a reading or a writing converter. Registering the converter instance as both might lead to unwanted results. For example, a Converter<String, Long> is ambiguous, although it probably does not make sense to try to convert all String instances into Long instances when writing. To let you force the infrastructure to register a converter for only one way, we provide @ReadingConverter and @WritingConverter annotations to be used in the converter implementation.

> Generally, we inspect the Converter implementations for the source and target types they convert from and to. Depending on whether one of those is a type the underlying data access API can handle natively, we register the converter instance as a reading or a writing converter. The following examples show a writing- and a read converter (note the difference is in the order of the qualifiers on Converter):

Which means (at least, based on my understanding), is that I could don't add `@WritingConverter` and it will work just fine without any unintended side effects? Is that right?
