### ISSUE TITLE
Ahead Of Time support for Querydsl

### ISSUE THREAD

**Issue by susimsek** [spring-projects/spring-data-mongodb#4244]
hi spring graphql teams.i am using spring graphql with querydsl. When I compile the project as native, I am getting an error as follows. Can you provide aot support for Querydsl?
<img width="1597" alt="image" src="https://user-images.githubusercontent.com/46258776/205240975-8df9d4f2-bd72-4620-bb4b-97aa0355f96d.png">

The reproduce example codes are shared via my Github, check [here.](https://github.com/susimsek/spring-graphql-samples) 

Spring boot version: 3.0.0
 Kotlin version: 1.7.21
 Java version: 17

**Comment by christophstrobl** [comment]
Thanks for reporting and the reproducer - we'll take care of it!
Please do not upload images of error messages but use code fences instead. Thank you.
```
Caused by: java.lang.IllegalStateException: No suitable constructor found on class org.springframework.data.mongodb.repository.support.ReactiveQuerydsIMongoPredicateExecutor to match the given arguments: org.springframework.data.mongodb.repository.support.MappingMongoEntityInformation,org.springframework.data.mongodb.core.ReactiveMongoTemplate.
Make sure you implement a constructor taking these
at org.springframework.data.repository.core.support.RepositoryFactorySupport.lambda$instantiateClass$6(RepositoryFactorySupport.java:572)~[spring-graphql-samples:3.0.0]
at java.base@17.0.5/java.util.Optional.orElseThrow(Optional.java:403)~[spring-graphql-samples:na]
at org.springframework.data.repository.core.support.RepositoryFactorySupport.instantiateClass(RepositoryFactorySupport.java:572)
~[spring-graphql-samples:3.0.0]
at org.springframework.data.mongodb.repository.support.ReactiveMongoRepositoryFactory.getRepositoryFragments(ReactiveMongoRepositoryFactory.java:106)
~[na:na]
at org.springframework.data.repository.core.support.RepositoryFactorySupport.getRepositoryComposition(RepositoryFactorySupport.java:428)~[spring-graphql-samples:3.0.0]
at org.springframework.data.repository.core.support.RepositoryFactorySupport.getRepository(RepositoryFactorySupport.java:293)
~[spring-graphql-samples:3.0.0]
at org. springframework.data.repository.core.support.RepositoryFactoryBeanSupport.lambda$afterPropertiesSet$5(RepositoryFactoryBeanSupport.java:279)~[spring-graphql-samples:3.0.0]
at org.springframework.data.util.Lazy.getNullable(Lazy.java:229)~[na:na]
at org.springframework.data.util.Lazy.get(Lazy.java:113)
~[na:na]
at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.afterPropertiesSet(RepositoryFactoryBeanSupport.java:285)~[spring-graphal-samples:3.0.0]
at org.springframework.data.mongodb.repository.support.ReactiveMongoRepositoryFactoryBean.afterPropertiesSet(ReactiveMongoRepositoryFactoryBean.java:116)~[spring-graphql-samples:4.0.0]
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1797)~[spring-graphal-samples:6.0.2]
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1747)~[spring-graphal-samples:6.0.2]
50 common frames omitted
```
