### ISSUE TITLE
java.lang.reflect.InaccessibleObjectException: Unable to make java.util.stream.ReferencePipeline

### ISSUE THREAD

**Issue by Liliandev** [spring-projects/spring-data-mongodb#4301]
I use this code and when i want to get results, an InaccessibleObjectException is throwed. I use JDK 17.

final MatchOperation identifiantsSpecifiques = Aggregation.match(Criteria.where("typeUtilisateur").in(IdentifiantSpecifiqueBuilder.TYPES_VALIDES.stream().map(Enum::name)));

final Aggregation aggregation = Aggregation.newAggregation(identifiantsSpecifiques);
 mongoTemplate.aggregate(aggregation, identifiantsCollectionName, EventAggregate.class).getRawResults();

![stacktrace](https://user-images.githubusercontent.com/4364899/220572176-e71083ef-64ff-4523-9f8a-9966c475786d.PNG)

And the stacktrace : 

java.lang.reflect.InaccessibleObjectException: Unable to make java.util.stream.ReferencePipeline$3(java.util.stream.ReferencePipeline,java.util.stream.AbstractPipeline,java.util.stream.StreamShape,int,java.util.function.Function) accessible: module java.base does not "opens java.util.stream" to unnamed module @5146bee3
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354) ~[na:na]
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297) ~[na:na]
	at java.base/java.lang.reflect.Constructor.checkCanSetAccessible(Constructor.java:188) ~[na:na]
	at java.base/java.lang.reflect.Constructor.setAccessible(Constructor.java:181) ~[na:na]
	at org.springframework.util.ReflectionUtils.makeAccessible(ReflectionUtils.java:202) ~[spring-core-5.3.24.jar:5.3.24]
	at org.springframework.data.mapping.PreferredConstructor.<init>(PreferredConstructor.java:64) ~[spring-data-commons-2.6.10.jar:2.6.10]
	at org.springframework.data.mapping.model.PreferredConstructorDiscoverer$Discoverers.buildPreferredConstructor(PreferredConstructorDiscoverer.java:222) ~[spring-data-commons-2.6.10.jar:2.6.10]
	at org.springframework.data.mapping.model.PreferredConstructorDiscoverer$Discoverers.access$200(PreferredConstructorDiscoverer.java:91) ~[spring-data-commons-2.6.10.jar:2.6.10]
	at org.springframework.data.mapping.model.PreferredConstructorDiscoverer$Discoverers$1.discover(PreferredConstructorDiscoverer.java:134) ~[spring-data-commons-2.6.10.jar:2.6.10]
	at org.springframework.data.mapping.model.PreferredConstructorDiscoverer.discover(PreferredConstructorDiscoverer.java:79) ~[spring-data-commons-2.6.10.jar:2.6.10]
	at org.springframework.data.mapping.model.BasicPersistentEntity.<init>(BasicPersistentEntity.java:113) ~[spring-data-commons-2.6.10.jar:2.6.10]
	at org.springframework.data.mongodb.core.mapping.BasicMongoPersistentEntity.<init>(BasicMongoPersistentEntity.java:84) ~[spring-data-mongodb-3.3.10.jar:3.3.10]
	at org.springframework.data.mongodb.core.mapping.MongoMappingContext.createPersistentEntity(MongoMappingContext.java:100) ~[spring-data-mongodb-3.3.10.jar:3.3.10]
	at org.springframework.data.mongodb.core.mapping.MongoMappingContext.createPersistentEntity(MongoMappingContext.java:41) ~[spring-data-mongodb-3.3.10.jar:3.3.10]
	at org.springframework.data.mapping.context.AbstractMappingContext.doAddPersistentEntity(AbstractMappingContext.java:430) ~[spring-data-commons-2.6.10.jar:2.6.10]
	at org.springframework.data.mapping.context.AbstractMappingContext.addPersistentEntity(AbstractMappingContext.java:406) ~[spring-data-commons-2.6.10.jar:2.6.10]
	at org.springframework.data.mapping.context.AbstractMappingContext.getPersistentEntity(AbstractMappingContext.java:291) ~[spring-data-commons-2.6.10.jar:2.6.10]
	at org.springframework.data.mapping.context.AbstractMappingContext.getPersistentEntity(AbstractMappingContext.java:209) ~[spring-data-commons-2.6.10.jar:2.6.10]
	at org.springframework.data.mapping.context.AbstractMappingContext.getPersistentEntity(AbstractMappingContext.java:92) ~[spring-data-commons-2.6.10.jar:2.6.10]
	at org.springframework.data.mapping.context.MappingContext.getRequiredPersistentEntity(MappingContext.java:74) ~[spring-data-commons-2.6.10.jar:2.6.10]
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.writeInternal(MappingMongoConverter.java:710) ~[spring-data-mongodb-3.3.10.jar:3.3.10]
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.write(MappingMongoConverter.java:661) ~[spring-data-mongodb-3.3.10.jar:3.3.10]
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.convertToMongoType(MappingMongoConverter.java:1431) ~[spring-data-mongodb-3.3.10.jar:3.3.10]
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.maybeConvertList(MappingMongoConverter.java:1457) ~[spring-data-mongodb-3.3.10.jar:3.3.10]
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.convertToMongoType(MappingMongoConverter.java:1386) ~[spring-data-mongodb-3.3.10.jar:3.3.10]
	at org.springframework.data.mongodb.core.convert.QueryMapper.delegateConvertToMongoType(QueryMapper.java:600) ~[spring-data-mongodb-3.3.10.jar:3.3.10]
	at org.springframework.data.mongodb.core.convert.QueryMapper.convertSimpleOrDocument(QueryMapper.java:545) ~[spring-data-mongodb-3.3.10.jar:3.3.10]
	at org.springframework.data.mongodb.core.convert.QueryMapper.getMappedValue(QueryMapper.java:480) ~[spring-data-mongodb-3.3.10.jar:3.3.10]
	at org.springframework.data.mongodb.core.convert.QueryMapper.getMappedKeyword(QueryMapper.java:401) ~[spring-data-mongodb-3.3.10.jar:3.3.10]
	at org.springframework.data.mongodb.core.convert.QueryMapper.getMappedObjectForField(QueryMapper.java:325) ~[spring-data-mongodb-3.3.10.jar:3.3.10]
	at org.springframework.data.mongodb.core.convert.QueryMapper.getMappedObject(QueryMapper.java:166) ~[spring-data-mongodb-3.3.10.jar:3.3.10]
	at org.springframework.data.mongodb.core.aggregation.TypeBasedAggregationOperationContext.getMappedObject(TypeBasedAggregationOperationContext.java:89) ~[spring-data-mongodb-3.3.10.jar:3.3.10]
	at org.springframework.data.mongodb.core.aggregation.TypeBasedAggregationOperationContext.getMappedObject(TypeBasedAggregationOperationContext.java:80) ~[spring-data-mongodb-3.3.10.jar:3.3.10]
	at org.springframework.data.mongodb.core.aggregation.MatchOperation.toDocument(MatchOperation.java:78) ~[spring-data-mongodb-3.3.10.jar:3.3.10]
	at org.springframework.data.mongodb.core.aggregation.AggregationOperation.toPipelineStages(AggregationOperation.java:55) ~[spring-data-mongodb-3.3.10.jar:3.3.10]
	at org.springframework.data.mongodb.core.aggregation.AggregationOperationRenderer.toDocument(AggregationOperationRenderer.java:56) ~[spring-data-mongodb-3.3.10.jar:3.3.10]
	at org.springframework.data.mongodb.core.aggregation.AggregationPipeline.toDocuments(AggregationPipeline.java:81) ~[spring-data-mongodb-3.3.10.jar:3.3.10]
	at org.springframework.data.mongodb.core.aggregation.Aggregation.toPipeline(Aggregation.java:716) ~[spring-data-mongodb-3.3.10.jar:3.3.10]
	at org.springframework.data.mongodb.core.AggregationUtil.createPipeline(AggregationUtil.java:112) ~[spring-data-mongodb-3.3.10.jar:3.3.10]
	at org.springframework.data.mongodb.core.MongoTemplate.doAggregate(MongoTemplate.java:2165) ~[spring-data-mongodb-3.3.10.jar:3.3.10]
	at org.springframework.data.mongodb.core.MongoTemplate.doAggregate(MongoTemplate.java:2140) ~[spring-data-mongodb-3.3.10.jar:3.3.10]
	at org.springframework.data.mongodb.core.MongoTemplate.aggregate(MongoTemplate.java:2134) ~[spring-data-mongodb-3.3.10.jar:3.3.10]
	at org.springframework.data.mongodb.core.MongoTemplate.aggregate(MongoTemplate.java:2035) ~[spring-data-mongodb-3.3.10.jar:3.3.10]

I tried with JDK 11 and have a loop on MongoDbConverter

Any idea ?
Many thanks for your help

**Comment by Liliandev** [comment]
I found the trouble. Sorry
