### ISSUE TITLE
MongoAnnotationProcessor doesn't find query class from another module class

### ISSUE THREAD

**Issue by exaucae** [spring-projects/spring-data-mongodb#4549]
I have a multimodule kotlin gradle project. A module called common defines the `Product`class with necessary QueryDSL annotations to generate related query class at runtime : 

````kt
package common.model

import com.querydsl.core.annotations.QueryEmbeddable
import kotlinx.serialization.Serializable
import org.springframework.data.mongodb.core.index.Indexed
import org.springframework.data.mongodb.core.mapping.Document

@Serializable
@QueryEmbeddable
@Document(collection = "products")
actual data class Product (@Indexed(unique = true) actual var name: String, actual var description: String? = null) : BaseModel()

````
My other module, called backend, uses that model and necessary query dsl libraries and processors to generate related query class at runtime:

````kt

dependencies {
    implementation(project(":common"))
    implementation(libs.spring.mongo.reactive)
    implementation("com.google.android.gms:play-services-tagmanager-v4-impl:18.0.3")
    developmentOnly("org.springframework.boot:spring-boot-devtools")
    annotationProcessor("org.springframework.boot:spring-boot-configuration-processor")
    implementation("com.querydsl:querydsl-mongodb:5.0.0") {
        exclude(group = "org.mongodb", module = "mongo-java-driver")
    }
    implementation(libs.querydsl.core)
    kapt(libs.com.querydsl.querydsl.apt)
    implementation(libs.com.querydsl.querydsl.apt)
}

kapt {
    keepJavacAnnotationProcessors = true
    annotationProcessor("org.springframework.data.mongodb.repository.support.MongoAnnotationProcessor")
}

````

Unfortunately, `MongoAnnotationProcessor` can't find related query class at runtime:

> Caused by: java.lang.IllegalArgumentException: Did not find a query class common.model.QProduct for domain class common.model.Product
	at org.springframework.data.querydsl.SimpleEntityPathResolver.createPath(SimpleEntityPathResolver.java:78) ~[spring-data-commons-3.1.3.jar:3.1.3]
	at org.springframework.data.mongodb.repository.support.ReactiveQuerydslMongoPredicateExecutor.<init>(ReactiveQuerydslMongoPredicateExecutor.java:83) ~[spring-data-mongodb-4.1.3.jar:4.1.3]
	at org.springframework.data.mongodb.repository.support.ReactiveQuerydslMongoPredicateExecutor.<init>(ReactiveQuerydslMongoPredicateExecutor.java:69) ~[spring-data-mongodb-4.1.3.jar:4.1.3]
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:na]
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[na:na]
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[na:na]
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:211) ~[spring-beans-6.0.11.jar:6.0.11]
	... 62 common frames omitted

Can the AP scan another module? If not, do I have alternatives here? The model is used across several other modules. Can't really hoist it in the backend module without duplicating it inn others too.

**Comment by mp911de** [comment]
Annotation processors are a Java Compiler concept. Your code is Kotlin and that is, why the annotation processor doesn't react. The MongoDB annotation processor provides merely a configuration to Querydsl's annotation-processor. 

You might want to reach out to the Querydsl team to check their stance on Kotlin annotation processor support.
