### ISSUE TITLE
Error creating bean with name 'mongoTemplate' defined in class path resource

### ISSUE THREAD

**Issue by sokoli1** [spring-projects/spring-data-mongodb#4605]
Spring can not create **mongoTemplate**  if specific name to the bean is given. When name attribute is removed, spring registers **mongoTemplate** bean successfully.

`org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mongoTemplate' defined in class path resource No matching factory method found on class factory bean 'MongoConfiguration'; factory method 'mongoTemplate()'. Check that a method with the specified name exists and that it is non-static.`

```
@Configuration
public class MongoConfiguration extends AbstractMongoClientConfiguration {

    @Bean(name = "newMongoDatabaseFactory")
    @Override
    public MongoDatabaseFactory mongoDbFactory() {
        return super.mongoDbFactory();
    }

    @Bean(name = "newMongoTemplate")
    @Override
    public MongoTemplate mongoTemplate(@Qualifier("newMongoDatabaseFactory") MongoDatabaseFactory databaseFactory, MappingMongoConverter converter) {
        return super.mongoTemplate(databaseFactory, converter);
    }
}
```

springboot-starter-web: 3.1.5
springboot-starter-data-mongo: 3.1.5
spring-data-mongodb: 4.1.5

**Comment by mp911de** [comment]
Care to include the full stack trace?

**Comment by sokoli1** [comment]
Here is the stack trace when running the application

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mongoTemplate' defined in class path resource [MongoConfiguration.class]: 
No matching factory method found on class [MongoConfiguration]: factory bean 'mongoConfiguration'; factory method 'mongoTemplate()'.
Check that a method with the specified name exists and that it is non-static.
    at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:622)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1332)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1162)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:560)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520)
    at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:325)
    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:323)
    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:973)
    at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:950)
    at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:616)
    at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146)
    at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:738)
    at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:440)
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295)

Process finished with exit code 1
```

Here is my **MongoConfigration** class:

```
@Configuration
@EnableMongoRepositories(mongoTemplateRef = "newMongoTemplate")
public class MongoConfiguration extends AbstractMongoClientConfiguration {

    @Override
    @Bean(name = "newMongoDatabaseFactory")
    public MongoDatabaseFactory mongoDbFactory() {
        return super.mongoDbFactory();
    }

    @Override
    @Bean("newMongoTemplate")
    public MongoTemplate mongoTemplate(@Qualifier("tagsMongoDatabaseFactory") MongoDatabaseFactory databaseFactory, MappingMongoConverter converter) {
        return super.mongoTemplate(databaseFactory, converter);
    }

    @Override
    protected String getDatabaseName() {
        return "db-name";
    }

    @Override
    public MongoClient mongoClient() {
        return MongoClients.create(new ConnectionString("db-uri"));
    }

    @Bean()
    MongoTransactionManager transactionManager(@Qualifier("newMongoDatabaseFactory") MongoDatabaseFactory dbFactory) {
        return new MongoTransactionManager(dbFactory);
    }
    
}
```

**Comment by christophstrobl** [comment]
The `AbstractMongoClientConfiguration` already defines a set of `@Bean` methods. Extending `MongoConfigurationSupport` gives you more control over the beans created and allows usage of additional `@Qualifier` annotations without unintended side effects.

```java
@Configuration
@EnableMongoRepositories(mongoTemplateRef = "newMongoTemplate")
public class MongoConfiguration extends MongoConfigurationSupport {

	@Bean(name = "newMongoDatabaseFactory")
	public MongoDatabaseFactory mongoDbFactory() {
		return new SimpleMongoClientDatabaseFactory(mongoClient(), getDatabaseName());
	}

	@Bean("newMongoTemplate")
	public MongoTemplate mongoTemplate(@Qualifier("newMongoDatabaseFactory") MongoDatabaseFactory databaseFactory, MappingMongoConverter converter) {
		return new MongoTemplate(databaseFactory, converter);
	}

	@Bean
	public MappingMongoConverter mappingMongoConverter(@Qualifier("newMongoDatabaseFactory") 
 MongoDatabaseFactory databaseFactory, MongoCustomConversions customConversions, MongoMappingContext mappingContext) {
		DbRefResolver dbRefResolver = new DefaultDbRefResolver(databaseFactory);
		MappingMongoConverter converter = new MappingMongoConverter(dbRefResolver, mappingContext);
		converter.setCustomConversions(customConversions);
		converter.setCodecRegistryProvider(databaseFactory);
		return converter;
	}

	@Bean()
	MongoTransactionManager transactionManager(@Qualifier("newMongoDatabaseFactory") MongoDatabaseFactory dbFactory) {
		return new MongoTransactionManager(dbFactory);
	}

	// ....
}
```

**Comment by sokoli1** [comment]
Thanks for the helpful suggestion.
Would you consider the issue I described as a bug, since it was working fine with spring-boot 2.7.x?

**Comment by mp911de** [comment]
We haven't structurally changed our configuration support so any changes observed in behavior are likely to come from Spring Framework (or Spring Boot).
