### ISSUE TITLE
Nested Interface-based projection fails with `ConverterNotFoundException`

### ISSUE THREAD

**Issue by ELMORABITYounes** [spring-projects/spring-data-mongodb#4609]
Starting from spring-data-mongodb 3.4.3 (spring boot 2.7.4) when trying to use interface-based recusive projeection as described [here](https://docs.spring.io/spring-data/mongodb/reference/repositories/projections.html#:~:text=Projections%20can%20be%20used%20recursively.%20If%20you%20want%20to%20include%20some%20of%20the%20Address%20information%20as%20well%2C%20create%20a%20projection%20interface%20for%20that%20and%20return%20that%20interface%20from%20the%20declaration%20of%20getAddress()%2C%20as%20shown%20in%20the%20following%20example%3A), a ConverterNotFoundException is thrown (see example below).

You can find [here](https://github.com/ELMORABITYounes/reactive-spring-data-mogodb-projection-issue) a simple project for reproducing the issue.

Note that the issue is only reproducible when using reactive repositories and not when using blocking repositories.

**Example**:

```
java.lang.AssertionError: expectation "expectNextMatches" failed (expected: onNext(); actual: onError(org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type [com.example.reactivemongoprojectionissue.bmodels.ApiSubTransaction] to type [com.example.reactivemongoprojectionissue.models.SubTransactionProjection]))
	at reactor.test.MessageFormatter.assertionError(MessageFormatter.java:115)
	at reactor.test.MessageFormatter.failPrefix(MessageFormatter.java:104)
	at reactor.test.MessageFormatter.fail(MessageFormatter.java:73)
	at reactor.test.MessageFormatter.failOptional(MessageFormatter.java:88)
	at reactor.test.DefaultStepVerifierBuilder.lambda$expectNextMatches$11(DefaultStepVerifierBuilder.java:556)
	at reactor.test.DefaultStepVerifierBuilder$SignalEvent.test(DefaultStepVerifierBuilder.java:2288)
	at reactor.test.DefaultStepVerifierBuilder$DefaultVerifySubscriber.onSignal(DefaultStepVerifierBuilder.java:1528)
	at reactor.test.DefaultStepVerifierBuilder$DefaultVerifySubscriber.onExpectation(DefaultStepVerifierBuilder.java:1476)
	at reactor.test.DefaultStepVerifierBuilder$DefaultVerifySubscriber.onError(DefaultStepVerifierBuilder.java:1129)
	at reactor.core.publisher.FluxUsingWhen$UsingWhenSubscriber.deferredError(FluxUsingWhen.java:398)
	at reactor.core.publisher.FluxUsingWhen$RollbackInner.onComplete(FluxUsingWhen.java:475)
	at reactor.core.publisher.Operators.complete(Operators.java:137)
	at reactor.core.publisher.MonoEmpty.subscribe(MonoEmpty.java:46)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4455)
	at reactor.core.publisher.FluxUsingWhen$UsingWhenSubscriber.onError(FluxUsingWhen.java:364)
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onError(MonoFlatMapMany.java:255)
	at reactor.core.publisher.FluxMap$MapSubscriber.onError(FluxMap.java:134)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:106)
	at reactor.core.publisher.Operators.error(Operators.java:198)
	at reactor.core.publisher.MonoError.subscribe(MonoError.java:53)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4455)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:103)
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onError(MonoFlatMapMany.java:255)
	at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.drain(FluxConcatMap.java:383)
	at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.onNext(FluxConcatMap.java:251)
	at reactor.core.publisher.FluxCreate$BufferAsyncSink.drain(FluxCreate.java:814)
	at reactor.core.publisher.FluxCreate$BufferAsyncSink.next(FluxCreate.java:739)
	at reactor.core.publisher.FluxCreate$SerializedFluxSink.next(FluxCreate.java:161)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)

```

**Comment by christophstrobl** [comment]
@ELMORABITYounes thanks for reporting and the reproducer. We'll have a look.

**Comment by christophstrobl** [comment]
confirmed - [context resolution](https://github.com/spring-projects/spring-data-mongodb/commit/52886e1680b8bc8ab3d0571c1590ace7560f4f1d#diff-01a701fba9cd274aff68eda141c9db9e8b21e7d07cea67b62ca2f18791950f10R1979-R1982) for the given property is breaking the interface projection for nested objects.
