### ISSUE TITLE
NPE when use MongoTemplate#updateFirst, MongoTemplate#updateMulti with Query#withHint

### ISSUE THREAD

**Issue by sitdownrightnow2552** [spring-projects/spring-data-mongodb#4656]
Mongo template throw npe when update using Query#withHint

[Bug repoduction repository](https://github.com/sitdownrightnow2552/Spring-Data-Mongo---Update-with-hint-NPE-error-reproduction)

```
java.lang.NullPointerException: Cannot invoke "org.bson.codecs.configuration.CodecRegistry.get(java.lang.Class)" because "codecRegistry" is null
	at org.bson.Document.toBsonDocument(Document.java:134)
	at com.mongodb.internal.connection.SplittablePayload$WriteRequestEncoder.encode(SplittablePayload.java:249)
	at com.mongodb.internal.connection.SplittablePayload$WriteRequestEncoder.encode(SplittablePayload.java:182)
	at org.bson.codecs.BsonDocumentWrapperCodec.encode(BsonDocumentWrapperCodec.java:63)
	at org.bson.codecs.BsonDocumentWrapperCodec.encode(BsonDocumentWrapperCodec.java:29)
	at com.mongodb.internal.connection.BsonWriterHelper.writeDocument(BsonWriterHelper.java:77)
	at com.mongodb.internal.connection.BsonWriterHelper.writePayload(BsonWriterHelper.java:59)
	at com.mongodb.internal.connection.CommandMessage.encodeMessageBodyWithMetadata(CommandMessage.java:162)
	at com.mongodb.internal.connection.RequestMessage.encode(RequestMessage.java:136)
	at com.mongodb.internal.connection.CommandMessage.encode(CommandMessage.java:59)
	at com.mongodb.internal.connection.InternalStreamConnection.sendAndReceive(InternalStreamConnection.java:360)
	at com.mongodb.internal.connection.UsageTrackingInternalConnection.sendAndReceive(UsageTrackingInternalConnection.java:114)
	at com.mongodb.internal.connection.DefaultConnectionPool$PooledConnection.sendAndReceive(DefaultConnectionPool.java:765)
	at com.mongodb.internal.connection.CommandProtocolImpl.execute(CommandProtocolImpl.java:76)
	at com.mongodb.internal.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:209)
	at com.mongodb.internal.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:115)
	at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:83)
	at com.mongodb.internal.connection.DefaultServer$OperationCountTrackingConnection.command(DefaultServer.java:307)
	at com.mongodb.internal.operation.MixedBulkWriteOperation.executeCommand(MixedBulkWriteOperation.java:395)
	at com.mongodb.internal.operation.MixedBulkWriteOperation.executeBulkWriteBatch(MixedBulkWriteOperation.java:259)
	at com.mongodb.internal.operation.MixedBulkWriteOperation.lambda$execute$2(MixedBulkWriteOperation.java:203)
	at com.mongodb.internal.operation.SyncOperationHelper.lambda$withSourceAndConnection$0(SyncOperationHelper.java:127)
	at com.mongodb.internal.operation.SyncOperationHelper.withSuppliedResource(SyncOperationHelper.java:152)
	at com.mongodb.internal.operation.SyncOperationHelper.lambda$withSourceAndConnection$1(SyncOperationHelper.java:126)
	at com.mongodb.internal.operation.SyncOperationHelper.withSuppliedResource(SyncOperationHelper.java:152)
	at com.mongodb.internal.operation.SyncOperationHelper.withSourceAndConnection(SyncOperationHelper.java:125)
	at com.mongodb.internal.operation.MixedBulkWriteOperation.lambda$execute$3(MixedBulkWriteOperation.java:188)
	at com.mongodb.internal.operation.MixedBulkWriteOperation.lambda$decorateWriteWithRetries$0(MixedBulkWriteOperation.java:146)
	at com.mongodb.internal.async.function.RetryingSyncSupplier.get(RetryingSyncSupplier.java:67)
	at com.mongodb.internal.operation.MixedBulkWriteOperation.execute(MixedBulkWriteOperation.java:207)
	at com.mongodb.internal.operation.MixedBulkWriteOperation.execute(MixedBulkWriteOperation.java:77)
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:173)
	at com.mongodb.client.internal.MongoCollectionImpl.executeSingleWriteRequest(MongoCollectionImpl.java:1085)
	at com.mongodb.client.internal.MongoCollectionImpl.executeUpdate(MongoCollectionImpl.java:1069)
	at com.mongodb.client.internal.MongoCollectionImpl.updateOne(MongoCollectionImpl.java:586)
	at org.springframework.data.mongodb.core.MongoTemplate.lambda$doUpdate$21(MongoTemplate.java:1752)
	at org.springframework.data.mongodb.core.MongoTemplate.execute(MongoTemplate.java:601)
	at org.springframework.data.mongodb.core.MongoTemplate.doUpdate(MongoTemplate.java:1725)
	at org.springframework.data.mongodb.core.MongoTemplate.updateFirst(MongoTemplate.java:1648)
```

Bug repoduction:
```java
package com.example.npe;

import org.bson.Document;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.data.mongodb.core.MongoTemplate;
import org.springframework.data.mongodb.core.index.CompoundIndexDefinition;
import org.springframework.data.mongodb.core.query.Criteria;
import org.springframework.data.mongodb.core.query.Query;
import org.springframework.data.mongodb.core.query.Update;

@SpringBootTest
class NpeApplicationTests {
    private static final Document Index = new Document("ok", 1);

    @Autowired
    MongoTemplate mongoTemplate;

    @BeforeEach
    void setup() {
        mongoTemplate.createCollection("test");
        final CompoundIndexDefinition indexDefinition = new CompoundIndexDefinition(Index);
        mongoTemplate.indexOps("test").ensureIndex(indexDefinition);

        mongoTemplate.insert(new Document("ok", true), "test");
    }

    @AfterEach
    void cleanup() {
        mongoTemplate.dropCollection("test");
    }

    @Test
    void queryWithHintShouldWork() {
        final var query = Query.query(Criteria.where("ok").is(true));
        query.withHint(Index);
        Assertions.assertTrue(mongoTemplate.findOne(query, Document.class, "test").getBoolean("ok"));
    }

    @Test
    void updateWithHintShouldFail() {
        final var query = Query.query(Criteria.where("ok").is(true));
        query.withHint(Index);
        // fail with npe
        Assertions.assertThrows(NullPointerException.class, () -> mongoTemplate.updateFirst(query, Update.update("update_ok", true), "test"));
        Assertions.assertThrows(NullPointerException.class, () -> mongoTemplate.updateMulti(query, Update.update("update_ok", true), "test"));
    }
}
```

**Comment by christophstrobl** [comment]
@sitdownrightnow2552 thank you for reporting. This seems to be an issue with the MongoDB driver as it can be reproduced with MongoDB native API.
```java
UpdateOptions options = new UpdateOptions();
options.hint(new Document("ok", 1));
mongoClient. ... .updateOne(new Document(), new Document("$set", ...), options);
```
Please reach out to the [MongoDB team](https://jira.mongodb.org/projects/JAVA/issues/) directly and leave a comment with the link to the jira issue on this issue for reference.
